# Pandas Essential Training

## Using pandas

In [71]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Installing collected packages: pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
Successfully installed pandas-2.3.1

In [74]:
!pip install numpy

Collecting numpy
  Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 1.7 MB/s eta 0:00:00
Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 25.4 MB/s eta 0:00:00
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.2 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.2 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.2 which is incompatible.
Successfully installed numpy-2.3.2

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.1'

In [ ]:
dir(pd)

In [ ]:
help(pd.read_csv)

In [ ]:
pd.read_csv?

Pandas documentation: https://pandas.pydata.org/docs/reference/index.html

## Reading tabular data into pandas

In [ ]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

In [ ]:
#from google.colab import files
#files.upload()

In [ ]:
!ls -la

In [ ]:
pd.read_csv?

In [ ]:
pd.read_csv('olympics_1896_2004.csv')

In [ ]:
pd.read_csv(filepath_or_buffer='olympics_1896_2004.csv')

In [ ]:
oo = pd.read_csv('olympics_1896_2004.csv')
oo

In [ ]:
oo = pd.read_csv('olympics_1896_2004.csv', skiprows=5)
oo

In [ ]:
filename = "olympics_1896_2004.csv"

In [ ]:
#from google.colab import files
#files.upload()

## Get an overview of the data and displaying it

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo

In [ ]:
oo.shape

In [ ]:
oo.shape?

In [ ]:
oo.head()

In [ ]:
oo.head?

In [ ]:
oo.head(3)

In [ ]:
oo.tail()

In [ ]:
oo.sample(5)

In [ ]:
oo.sample?

In [ ]:
oo.info()

In [ ]:
oo.describe()

In [ ]:
pd.get_option("display.max_rows")

In [ ]:
pd.set_option("display.max_rows", None)
oo

In [ ]:
pd.set_option("display.max_rows", 60)
oo

In [ ]:
pd.get_option("display.max_columns")

In [ ]:
pd.get_option("display.width")

In [ ]:
pd.set_option("display.width", 100)

## Select a Series (column)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
type(oo)

In [ ]:
oo["Discipline"]

In [ ]:
oo['Discipline']

In [ ]:
#oo["discipline"]

In [ ]:
type(oo["Discipline"])

In [ ]:
oo.Discipline

In [ ]:
oo.columns

In [ ]:
oo["Athlete Name"]

In [ ]:
#oo.Athlete Name

In [ ]:
oo.sample(3)

In [ ]:
oo.Year.unique()

In [ ]:
oo.Year.unique?

In [ ]:
oo.Sport.unique()

In [ ]:
oo.sample(3)

In [ ]:
oo.Year.value_counts()

In [ ]:
oo.Year.value_counts?

In [ ]:
oo.Year.value_counts(normalize=True)

## Challenge

Answer the following questions. Indicate the Pandas command where relevant.

1.   What is the time range covered in this dataset?
2.   The Olympics take place every 4 years. Why are there missing years?
3.   What are the types of medals awarded?
4.   Across all of the Olympic Games, how many Gold, Silver and Bronze medals have there been?
5.   Why are there not an equal number of Gold, Silver and Bronze medals?
6.   There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?
7.   What are the different NOCs (National Olympic Committees)
8.   What does the NOC 'ZZX' represent?

##Solution

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

1. What is the time range covered in this dataset?

In [ ]:
oo.Year.unique()

2. The Olympics take place every 4 years. Why are there missing years?
- World War 1: 1914-1918
- World War 2: 1939-1945

3. What are the types of medals awarded?

In [ ]:
oo.Medal.unique()

4. Across all of the Olympics, how many Gold, Silver and Bronze medals have there been?

In [ ]:
oo.Medal.value_counts()

5. Why are there not an equal number of Gold, Silver and Bronze medals?
- Tied results
- Team events
- Disqualifications

In [ ]:
oo.head(10)

6. There are more Gold medals than Silver, and more Silver than Bronze. Why might that be?

Men's 100km cycling
- https://en.wikipedia.org/wiki/Cycling_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_kilometres
- https://en.wikipedia.org/wiki/Aristidis_Konstantinidis

Men's 100m freestyle (1896)
- https://en.wikipedia.org/wiki/Swimming_at_the_1896_Summer_Olympics_%E2%80%93_Men%27s_100_metre_freestyle

7. What are the different NOCs (National Olympic Committees)

In [ ]:
oo.NOC.unique()

8. What does the NOC 'ZZX' represent?
- https://en.wikipedia.org/wiki/Mixed_teams_at_the_Olympics

## Python Lists and Dictionaries

In [ ]:
medals = ["Gold", "Silver", "Bronze"]
medals

In [ ]:
type(medals)

In [ ]:
position = {"First": "Gold",
            "Second": "Silver",
            "Third": "Bronze"
}
position

In [ ]:
type(position)

In [ ]:
position["First"]

## Rename a series (or column)

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
mapper = {"Athlete Name": "Athlete_Name",
          "Event Gender": "Event_Gender"}

In [ ]:
oo.rename?

In [ ]:
oo.rename(columns=mapper)

In [ ]:
oo.sample(3)

In [ ]:
oo = oo.rename(columns=mapper)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5).rename(columns=mapper)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.rename(columns={"Athlete Name": "Athlete_Name", "Event Gender": "Event_Gender"})
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.columns

In [ ]:
column_names = ['Year', 'City', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
       'Event', 'Event_Gender', 'Medal', 'Position']
oo.columns = column_names
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5, names=column_names)
oo.head()

In [ ]:
oo = pd.read_csv(filename, skiprows=5, names=column_names, header=0)
oo.head()

## Remove a Series (column) or row

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.sample(3)

In [ ]:
oo.drop('Position', axis=1)

In [ ]:
#oo.drop('Position', axis=0)

In [ ]:
oo.sample(3)

In [ ]:
oo = oo.drop('Position', axis=1)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5).drop('Position', axis=1)
oo.sample(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo = pd.read_csv(filename, skiprows=5)
oo.drop('Position', axis=1, inplace=True)
oo.sample(3)

In [ ]:
#oo = (pd.read_csv(filename, skiprows=5)
#      .drop('Position', axis=1, inplace=True)
#)
#oo.sample(3)

In [ ]:
oo.drop?

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop(2, axis=0)
)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop([0, 1, 3], axis=0)
)
oo.head(3)

In [ ]:
oo = oo.drop(['City', 'Sport'], axis=1)
oo.head(3)

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [ ]:
pd.merge?

In [ ]:
pd.concat?

In [ ]:
oo.groupby?

## Filtering rows for a single condition

In [4]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.2 which is incompatible.
arviz 0.22.0 requires pandas>=2.1.0, but you have pandas 2.0.2 which is incompatible.
mizani 0.13.5 requires pandas>=2.2.0, but you have pandas 2.0.2 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.0.2 which is incompatible.
xarray 2025.7.1 requires pandas>=2.2, but you have pandas 2.0.2 which is incompatible.
--2025-08-19 00:40:57--  https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv [following]
--2025-08-19 00:40:57--  https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2398388 (2.3M) [text/plain]
Saving to: ‘olympics_1896_2004.csv’

olympics_1896_2004. 100%[===================>]   2.29M  --.-KB/s    in 0.07s

2025-08-19 00:40:57 (30.7 MB/s) - ‘olympics_1896_2004.csv’ saved [2398388/2398388]

Installed all of the necessary files for this section ...

In [5]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
2825,1920,Antwerp,Wrestling,Wrestling Free.,"MEYER, Frederick Julius",USA,Men,+ 80kg (heavyweight),M,Bronze
8788,1952,Helsinki,Gymnastics,Artistic G.,"SHAMRAI, Galina",URS,Women,team competition,W,Gold
23841,2000,Sydney,Canoe / Kayak,Canoe / Kayak F,"VERECKEI, Akos",HUN,Men,K-4 1000m (kayak four),M,Gold

In [ ]:
type(True)

In [ ]:
type(False)

In [ ]:
oo.Year.dtype

In [6]:
first_olympics = (oo.Year == 1896)
first_olympics

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

0         True
1         True
2         True
3         True
4         True
         ...
27169    False
27170    False
27171    False
27172    False
27173    False
Name: Year, Length: 27174, dtype: bool

In [7]:
oo[first_olympics]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver

In [8]:
oo[oo.Year == 1896]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver

In [9]:
oo[oo.Year < 1896]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

Empty DataFrame
Columns: [Year, City, Sport, Discipline, Athlete Name, NOC, Gender, Event, Event Gender, Medal]
Index: []

In [10]:
oo[(oo.Year <= 1896)]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver

## Filter rows for multiple conditions

In [11]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

Installed all of the necessary files for this section ...

In [12]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.tail(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [13]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year             int64
City            object
Sport           object
Discipline      object
Athlete Name    object
NOC             object
Gender          object
Event           object
Event Gender    object
Medal           object
dtype: object

In [14]:
oo[oo.City == 'Athens']

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [ ]:
#oo[oo.City == Athens]

In [17]:
oo[(oo.Year == 1896) | (oo.Year == 2004)].Year.unique()

array([1896, 2004])

In [18]:
oo[(oo.City == 'Athens') & (oo.Year == 2004)]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
25176,2004,Athens,Judo,Judo,"PERTELSON, Indrek",EST,Men,+ 100kg (heavyweight),M,Bronze
25177,2004,Athens,Judo,Judo,"VAN DER GEEST, Dennis",NED,Men,+ 100kg (heavyweight),M,Bronze
25178,2004,Athens,Judo,Judo,"SUZUKI, Keiji",JPN,Men,+ 100kg (heavyweight),M,Gold
25179,2004,Athens,Judo,Judo,"TMENOV, Tamerlan",RUS,Men,+ 100kg (heavyweight),M,Silver
25180,2004,Athens,Weightlifting,Weightlifting,"CHOLAKOV, Velichko",BUL,Men,+ 105kg,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [19]:
oo[(oo.City == 'Athens') & ~(oo.Year == 1896)]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
25176,2004,Athens,Judo,Judo,"PERTELSON, Indrek",EST,Men,+ 100kg (heavyweight),M,Bronze
25177,2004,Athens,Judo,Judo,"VAN DER GEEST, Dennis",NED,Men,+ 100kg (heavyweight),M,Bronze
25178,2004,Athens,Judo,Judo,"SUZUKI, Keiji",JPN,Men,+ 100kg (heavyweight),M,Gold
25179,2004,Athens,Judo,Judo,"TMENOV, Tamerlan",RUS,Men,+ 100kg (heavyweight),M,Silver
25180,2004,Athens,Weightlifting,Weightlifting,"CHOLAKOV, Velichko",BUL,Men,+ 105kg,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [20]:
first_men_100m = oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')]
first_men_100m

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver

In [21]:
oo[(oo.Year == 1896) & (oo.Gender == 'Men') & (oo.Event == '100m')][["Year", "Athlete Name", "NOC", "Event", "Medal"]]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

   Year      Athlete Name  NOC Event   Medal
2  1896     LANE, Francis  USA  100m  Bronze
3  1896  SZOKOLYI, Alajos  HUN  100m  Bronze
4  1896     BURKE, Thomas  USA  100m    Gold
5  1896    HOFMANN, Fritz  GER  100m  Silver

In [22]:
first_men_100m[["Year", "Athlete Name", "NOC", "Event", "Medal"]]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

   Year      Athlete Name  NOC Event   Medal
2  1896     LANE, Francis  USA  100m  Bronze
3  1896  SZOKOLYI, Alajos  HUN  100m  Bronze
4  1896     BURKE, Thomas  USA  100m    Gold
5  1896    HOFMANN, Fritz  GER  100m  Silver

## Using String methods

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [23]:
oo["Athlete Name"].str.lower()

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

0             flameng, léon
1        kolettis, georgios
2             lane, francis
3          szokolyi, alajos
4             burke, thomas
                ...
27169    logounova, tatiana
27170         sivkova, anna
27171        bokel, claudia
27172       duplitzer, imke
27173     heidemann, britta
Name: Athlete Name, Length: 27174, dtype: object

In [24]:
oo.Event.unique()

array(['100km', '100m', '100m freestyle', '100m freestyle for sailors',
       '10km', '110m hurdles', '12-hour race', '1200m freestyle', '1500m',
       '1km time trial', '25m army pistol',
       '25m rapid fire pistol (60 shots)', '400m', '400m freestyle',
       '50m pistol (60 shots)', '800m', 'Sprint indivual',
       'army rifle, 200m', 'army rifle, 300m', 'discus throw', 'doubles',
       'foil individual', 'foil, masters', 'heavyweight - one hand lift',
       'heavyweight - two hand lift', 'high jump', 'horizontal bar',
       'individual road race', 'long jump', 'marathon', 'open event',
       'parallel bars', 'pole vault', 'pommel horse', 'rings',
       'rope climbing', 'sabre individual', 'shot put', 'singles',
       'team, horizontal bar', 'team, parallel bars', 'triple jump',
       'vault', '0.5-1t', '10-20t', '1500m freestyle', '200m',
       '200m backstroke', '200m freestyle', '200m hurdles',
       '200m obstacle event', '200m team swimming', '25 kilometres',
       '3-10t', '3000m steeplechase', '4000m freestyle',
       '4000m steeplechase', '400m hurdles', '5000m team',
       '50m army pistol, team', '60m', 'army rifle, 300m, 3 positions',
       'army rifle, 300m, kneeling', 'army rifle, 300m, prone',
       'army rifle, 300m, standing', 'au chapelet, 33m',
       'au chapelet, 50m', 'au cordon doré, 33m', 'au cordon doré, 50m',
       'cesta punta', 'cricket', 'double', 'eight with coxswain (8+)',
       'football', 'four-oared shell with coxswain (4-)',
       'free rifle, team', 'hammer throw', 'high jump, standing',
       'individual', 'individual 1 ball', 'individual 2 balls',
       'individual all-round', 'long jump individual',
       'long jump, standing', 'mixed doubles', 'open class',
       'pair-oared shell with coxswain (2+)', 'polo', 'rugby',
       'sabre, masters', 'single sculls (1x)', 'sur la perche à la herse',
       'sur la perche à la pyramide', 'trap (125 targets)',
       'triple jump, standing', 'tug of war', 'underwater swimming',
       'water polo', 'épée individual', 'épée, amateurs and masters',
       'épée, masters', '+ 71.67kg (heavyweight)',
       '- 47.63kg (flyweight)', '- 47.6kg (light-flyweight)',
       '1 mile (1609.3m)', '1/2 mile (804.7m)', '1/3 mile (536.5m)',
       '1/4 mile (402.3m)', '100m backstroke', '10m platform',
       '2 miles (3.218km)', '25 miles (40.232km)', '400m breaststroke',
       '47.6 - 52.16kg (flyweight)', '47.63 - 52.16kg (bantamweight)',
       '4miles team', '4x50y freestyle relay', '5 miles (8.046km)',
       '50y freestyle (45.72m)', '52.16 - 56.7kg (bantamweight)',
       '52.16 - 56.7kg (featherweight)', '56.7 - 61.23kg (featherweight)',
       '56.7 - 61.24kg (lightweight)', '56lb weight throw (25.4kg)',
       '61.23 - 65.77kg (lightweight)', '61.24 - 65.77kg (welterweight)',
       '65.77 - 71.67kg (middleweight)', '65.77 - 71.67kg (welterweight)',
       '880y freestyle (804.66m)', 'all-around Dumbbell contest',
       'club swinging', 'combined 3 events', 'combined 4 events',
       'coxless pair (2-)', 'decathlon',
       'double american round (60y - 50y - 40y)',
       'double columbia round (50y - 40y - 30y)',
       'double national round (60y - 50y)', 'double sculls (2x)',
       'double york round (100y - 80y - 60y)', 'foil team',
       'four without coxswain (4-)', 'lacrosse', 'plunge for distance',
       'stick, single', 'team', 'team competition', 'team round 60y',
       'teams FITA round', 'triathlon (long jump / shot put / 100 yards)',
       '+ 73kg (heavyweight)', '+ 93kg (super heavyweight)',
       '- 52.62kg (bantamweight)', '- 54kg (bantamweight)',
       '- 66.6kg (lightweight)', '1000y free rifle, prone',
       '100m running deer, double shots',
       '100m running deer, single shots',
       '100m running deer, single shots, team', '10miles walk (16093m)',
       '12m', '1980 yards Pursuit, Team', '2000m tandem',
       '200m breaststroke', '20km',
       '25y small bore rifle, disappearing target',
       '25y small bore rifle, moving target',
       '300m free rifle 3 positions (3x40 shots)', '3200m steeplechase',
       '3500m walk', '3m springboard', '3miles team (4828m)',
       '4x200m freestyle relay', '4x400m relay', '5 miles (8047m)',
       '50+100y small bore rifle, team', '5000m',
       '50m rifle prone (60 shots)', '50y army pistol, team',
       '52.62 - 57.15kg (featherweight)', '54 - 60.3kg (featherweight)',
       '57.15 - 63.5kg (lightweight)', '60.3 - 66.6kg (lightweight)',
       '63.5 - 71.67kg (middleweight)', '66.6 - 73kg (middleweight)',
       '6m', '73 - 93kg (light-heavyweight)', '7m', '8m', '8m class C',
       'One lap (660y) sprint', 'class B up to 60 feet',
       'clay pigeons, team', 'continental style 50m',
       'discus throw ancient style', 'doubles indoor', 'hockey',
       'javelin throw', 'javelin throw freestyle',
       'national round (60y - 50y)', 'open class A', 'pairs',
       'rifle, team', 'sabre team', 'singles indoor', 'special figures',
       'york round (100y - 80y - 60y)', 'épée team',
       '+ 82.5kg (super heavyweight)', '- 60kg (featherweight)', '10000m',
       '10000m walk', '10m', '25m small bore rifle, team',
       '25m small rifle', '3000m team', '30m army pistol, team',
       '4x100m freestyle relay', '4x100m relay',
       '50m small bore rifle, team', '60 - 67.5kg (lightweight)',
       '600m free rifle', '67.5 - 75kg (middleweight)',
       '75 - 82.5kg (light-heavyweight)', 'Individual competition',
       'coxed fours Jugriggers', 'cross country individual',
       'cross country team', 'discus throw, both hands',
       'individual time trial', 'javelin throw, both hands',
       'mixed doubles indoor', 'pentathlon', 'plain high diving',
       'shot put, both hands', 'team time trial', 'team, Swedish system',
       'team, free system', '+ 79.38kg (heavyweight)',
       '+ 80kg (heavyweight)',
       '+ 82.5kg, one-two hand 3 events (heavyweight)',
       '+ 82kg (super heavyweight)', '- 50.8kg (flyweight)',
       '- 60kg, one-two hand 3 events (featherweight)',
       '100m running deer, double shots, team', '10m (rating 1907)',
       '10m (rating 1919)', '12 foot dinghy', '12m (rating 1907)',
       '12m (rating 1919)', '18 foot dinghy',
       '300+600m free rifle, team, prone', '3000m walk',
       '300m free rifle, prone, team', '300m free rifle, standing, team',
       '30m sq', '40m sq', '50.8 - 53.52kg (bantamweight)', '50km',
       '50m small bore rifle, standing, individual',
       '53.52 - 57.15kg (featherweight)', '57.15 - 61.24kg (lightweight)',
       '6.5m (rating 1919)',
       '60 - 67.5kg, one-two hand 3 events (lightweight)',
       '600m free rifle, prone', '600m free rifle, team',
       '61.24 - 66.68kg (welterweight)', '66.68 - 72.57kg (middleweight)',
       '67.5 - 75kg, one-two hand 3 events (middleweight)',
       '6m (rating 1907)', '6m (rating 1919)',
       '72.57 - 79.38kg (light-heavyweight)',
       '75 - 80kg (light-heavyweight)',
       '75 - 82.5kg, one-two hand 3 e. (light-heavyweight)',
       '75 - 82kg (light-heavyweight)', '8m (rating 1907)',
       '8m (rating 1919)', 'Team Pursuit (4000m)',
       'figure riding individual', 'figure riding team',
       'fixed bird target large birds',
       'fixed bird target large birds teams',
       'fixed bird target small bird, teams',
       'fixed bird target small birds', 'ice hockey',
       'moving bird target 28m teams', 'moving bird target 33m teams',
       'moving bird target 50m teams', 'moving bird target, 28m',
       'moving bird target, 33m', 'moving bird target, 50m',
       '+ 82.5kg, one-two hand 5 events (heavyweight)',
       '+ 87kg (heavyweight)', '- 56kg (bantamweight)',
       '- 58kg (bantamweight)',
       '- 60kg, one-two hand 5 events (featherweight)',
       '400, 600, 800m free rifle, team', '56 - 61kg (featherweight)',
       '58 - 62kg (featherweight)',
       '60 - 67.5kg, one-two hand 5 events (lightweight)',
       '600m free rifle, individual', '61 - 66kg (lightweight)',
       '62 - 67.5kg (lightweight)', '66 - 72kg (welterweight)',
       '67.5 - 75kg, one-two hand 5 events (middleweight)',
       '72 - 79kg (middleweight)',
       '75 - 82.5kg, one-two hand 5 e. (light-heavyweight)',
       '79 - 87kg (light-heavyweight)', 'Sidehorse vault',
       'olympic class monotype', '+ 82.5kg, total (heavyweight)',
       '- 60kg, total (featherweight)', '12 foot dinghy individual',
       '1km Pursuit', '58 - 60kg (featherweight)',
       '60 - 67.5kg, total (lightweight)',
       '67.5 - 75kg, total (middleweight)',
       '75 - 82.5kg, total (light-heavyweight)',
       '+ 87kg (super heavyweight)', '50.8 - 54kg (bantamweight)',
       '50km walk', '54 - 57.15kg (featherweight)', '80m hurdles',
       'floor exercises', 'indian clubs', 'tumbling',
       'two-person keelboat open (Star)', 'C-1 1000m (canoe single)',
       'C-2 10000m', 'C-2 1000m (canoe double)', 'K-1 10000m',
       'K-1 1000m (kayak single)', 'K-2 10000m',
       'K-2 1000m (kayak double)', 'basketball', 'folding K-1 10000m',
       'folding K-2 10000m', 'handball', '- 51kg (flyweight)',
       '- 52kg (flyweight)', '- 56kg, total (bantamweight)',
       '51 - 54kg (bantamweight)', '52 - 57kg (bantamweight)',
       '54 - 58kg (featherweight)', '56 - 60kg, total (featherweight)',
       '57 - 61kg (featherweight)', '57 - 63kg (featherweight)',
       '58 - 62kg (lightweight)', '61 - 67kg (lightweight)',
       '62 - 67kg (welterweight)', '63 - 67kg (lightweight)',
       '67 - 73kg (middleweight)', '67 - 73kg (welterweight)',
       '73 - 79kg (middleweight)', '73 - 80kg (light-heavyweight)',
       'C-1 10000m', 'K-1 500m (kayak single)', 'dragon', 'firefly class',
       'swallow (golondrina)', '+ 81kg (heavyweight)',
       '+ 90kg, total (heavyweight)',
       '100m running deer, single/double shots', '5.5m',
       '50m rifle 3 positions (3x40 shots)', '54 - 57kg (featherweight)',
       '57 - 60kg (lightweight)', '60 - 63.5kg (light-welterweight)',
       '63.5 - 67kg (welterweight)', '67 - 71kg (light-middleweight)',
       '71-75kg', '75 - 81kg (light-heavyweight)',
       '82.5 - 90kg, total (middle-heavyweight)', 'Team competition',
       'balance beam', 'single-handed dinghy (Finn)',
       'team, portable apparatus', 'uneven bars', '100m butterfly',
       '200m butterfly', '20km walk', 'sharpie 12m2',
       '4x100m medley relay', 'K-1 4x500m', 'K-2 500m (kayak double)',
       'flying dutchman', '+ 97kg (heavyweight)',
       '+ 97kg (super heavyweight)', '- 68kg (lightweight)',
       '400m individual medley', '63 - 70kg (lightweight)',
       '68 - 80kg (middleweight)', '70 - 78kg (welterweight)',
       '78 - 87kg (middleweight)', '87 - 97kg (light-heavyweight)',
       'Individual Pursuit', 'K-4 1000m (kayak four)', 'open category',
       'volleyball', '- 48kg (light-flyweight)', '100m breaststroke',
       '200m individual medley', '48 - 51kg (flyweight)',
       '800m freestyle', 'skeet (125 targets)',
       '+ 100kg (super heavyweight)',
       '+ 110kg, total (super heavyweight)', '+ 93kg (heavyweight)',
       '- 52kg, total (flyweight)', '- 63kg (lightweight)',
       '100m hurdles', '48 - 52kg (flyweight)',
       '50m running target (30+30 shots)',
       '52 - 56kg, total (bantamweight)', '57 - 62kg (featherweight)',
       '62 - 68kg (lightweight)', '63 - 70kg (half-middleweight)',
       '68 - 74kg (welterweight)', '70 - 80kg (middleweight)',
       '74 - 82kg (middleweight)', '80 - 93kg (half-heavyweight)',
       '82 - 90kg (light-heavyweight)', '90 - 100kg (heavyweight)',
       '91 - 110kg, total (heavyweight)', 'C-1 (canoe single)',
       'C-2 (canoe double)', 'K-1 (kayak single)',
       'fleet/match race keelboat open (Soling)', 'individual FITA round',
       'tempest', '470 - Two Person Dinghy', 'C-1 500m (canoe single)',
       'C-2 500m (canoe double)', 'Tornado - Multihull',
       'pair without coxswain (2-)',
       'quadruple sculls with coxswain (4x)',
       'quadruple sculls without coxswain (4x)', '+ 95kg (heavyweight)',
       '- 60 kg', '100 - 110kg, total (heavyweight)',
       '60 - 65kg (half-lightweight)', '65 - 71kg (lightweight)',
       '71 - 78kg (half-middleweight)', '78 - 86kg (middleweight)',
       '86 - 95kg (half-heavyweight)',
       '90 - 100kg, total (first-heavyweight)',
       '+ 91kg (super heavyweight)', '10m air rifle (40 shots)',
       '10m air rifle (60 shots)', '25m pistol (30+30 shots)', '3000m',
       '50m rifle 3 positions (3x20 shots)', '81 - 91kg (heavyweight)',
       'K-4 500m (kayak four)', 'Points Race', 'board (windglider)',
       'duet', 'heptathlon', 'solo', '100 - 130kg (super heavyweight)',
       '10m air pistol (40 shots)', '10m air pistol (60 shots)',
       '50m freestyle', 'board (division II)', 'sprint',
       '+ 72kg (heavyweight)', '- 48kg (extra-lightweight)',
       '48 - 52kg (half-lightweight)', '52 - 56kg (lightweight)',
       '56 - 61kg (half-middleweight)', '61 - 66kg (middleweight)',
       '66 - 72kg (half-heavyweight)', 'baseball', 'board (lechner)',
       'coxless four (4-)', 'individual (FITA Olympic round - 70m)',
       'individual pursuit', 'single-handed dinghy (Europe)',
       'team (FITA Olympic round - 70m)', '+ 100kg (heavyweight)',
       '+ 108kg, total (super heavyweight)', '- 54kg, total (flyweight)',
       '54 - 59kg, total (bantamweight)',
       '59 - 64kg, total (featherweight)', '60 - 66kg (half-lightweight)',
       '64 - 70kg, total (lightweight)', '66 - 73kg (lightweight)',
       '70 - 76kg, total (middleweight)', '73 - 81kg (half-middleweight)',
       '76 - 83kg, total (light-heavyweight)', '81 - 90kg (middleweight)',
       '83 - 91kg, total (middle-heavyweight)',
       '90 - 100kg (half-heavyweight)',
       '91 - 99kg, total (first-heavyweight)',
       '99 - 108kg, total (heavyweight)', 'beach volleyball',
       'board (Mistral)', 'cross-country', 'double trap (120 targets)',
       'double trap (150 targets)', 'group competition',
       'lightweight coxless four (4-)', 'lightweight double sculls (2x)',
       'points race', 'single-handed dinghy open (Laser)', 'softball',
       '+ 105kg', '+ 67 kg', '+ 75kg', '+ 78kg (heavyweight)', '+ 80 kg',
       '- 49 kg', '- 58 kg', '105kg', '10m running target (30+30 shots)',
       '20km race walk', '48 - 54kg', '48kg', '49 - 57 kg',
       '49er - Skiff', '500m time trial', '52 - 57kg (lightweight)',
       '53kg', '54 - 58kg', '56kg', '57 - 63kg (half-middleweight)',
       '57 - 67 kg', '58 - 63kg', '58 - 68 kg', '58kg', '62kg',
       '63 - 69kg', '63 - 70kg (middleweight)', '63kg', '68 - 80 kg',
       '69 - 76kg', '69kg', '70 - 78kg (half-heavyweight)', '75kg',
       '76 - 85kg', '77kg', '85 - 97kg', '85kg', '94kg', '97 - 130kg',
       'Individual', 'Keirin', 'Madison', 'Olympic Sprint',
       'skeet (75 targets)', 'synchronized diving 10m platform',
       'synchronized diving 3m springboard', 'trap (75 targets)',
       '- 48 kg', '- 48kg', '- 55kg', '48 - 55kg',
       '48kg (light flywieght)', '55 - 60kg', '55 - 63kg', '60 - 64 kg',
       '60 - 66kg', '63 - 72kg', '64 - 69 kg', '66 - 74kg', '69 - 75 kg',
       '74 - 84kg', '84 - 96kg', '96 - 120kg', 'Star - Keelboat',
       'Team Sprint', 'Yngling - Keelboat'], dtype=object)

In [25]:
oo.Event.str.capitalize()

0            100km
1            100km
2             100m
3             100m
4             100m
           ...
27169    Épée team
27170    Épée team
27171    Épée team
27172    Épée team
27173    Épée team
Name: Event, Length: 27174, dtype: object

In [27]:
oo.Event = oo.Event.str.capitalize()
oo.Event.unique()

array(['100km', '100m', '100m freestyle', '100m freestyle for sailors',
       '10km', '110m hurdles', '12-hour race', '1200m freestyle', '1500m',
       '1km time trial', '25m army pistol',
       '25m rapid fire pistol (60 shots)', '400m', '400m freestyle',
       '50m pistol (60 shots)', '800m', 'Sprint indivual',
       'Army rifle, 200m', 'Army rifle, 300m', 'Discus throw', 'Doubles',
       'Foil individual', 'Foil, masters', 'Heavyweight - one hand lift',
       'Heavyweight - two hand lift', 'High jump', 'Horizontal bar',
       'Individual road race', 'Long jump', 'Marathon', 'Open event',
       'Parallel bars', 'Pole vault', 'Pommel horse', 'Rings',
       'Rope climbing', 'Sabre individual', 'Shot put', 'Singles',
       'Team, horizontal bar', 'Team, parallel bars', 'Triple jump',
       'Vault', '0.5-1t', '10-20t', '1500m freestyle', '200m',
       '200m backstroke', '200m freestyle', '200m hurdles',
       '200m obstacle event', '200m team swimming', '25 kilometres',
       '3-10t', '3000m steeplechase', '4000m freestyle',
       '4000m steeplechase', '400m hurdles', '5000m team',
       '50m army pistol, team', '60m', 'Army rifle, 300m, 3 positions',
       'Army rifle, 300m, kneeling', 'Army rifle, 300m, prone',
       'Army rifle, 300m, standing', 'Au chapelet, 33m',
       'Au chapelet, 50m', 'Au cordon doré, 33m', 'Au cordon doré, 50m',
       'Cesta punta', 'Cricket', 'Double', 'Eight with coxswain (8+)',
       'Football', 'Four-oared shell with coxswain (4-)',
       'Free rifle, team', 'Hammer throw', 'High jump, standing',
       'Individual', 'Individual 1 ball', 'Individual 2 balls',
       'Individual all-round', 'Long jump individual',
       'Long jump, standing', 'Mixed doubles', 'Open class',
       'Pair-oared shell with coxswain (2+)', 'Polo', 'Rugby',
       'Sabre, masters', 'Single sculls (1x)', 'Sur la perche à la herse',
       'Sur la perche à la pyramide', 'Trap (125 targets)',
       'Triple jump, standing', 'Tug of war', 'Underwater swimming',
       'Water polo', 'Épée individual', 'Épée, amateurs and masters',
       'Épée, masters', '+ 71.67kg (heavyweight)',
       '- 47.63kg (flyweight)', '- 47.6kg (light-flyweight)',
       '1 mile (1609.3m)', '1/2 mile (804.7m)', '1/3 mile (536.5m)',
       '1/4 mile (402.3m)', '100m backstroke', '10m platform',
       '2 miles (3.218km)', '25 miles (40.232km)', '400m breaststroke',
       '47.6 - 52.16kg (flyweight)', '47.63 - 52.16kg (bantamweight)',
       '4miles team', '4x50y freestyle relay', '5 miles (8.046km)',
       '50y freestyle (45.72m)', '52.16 - 56.7kg (bantamweight)',
       '52.16 - 56.7kg (featherweight)', '56.7 - 61.23kg (featherweight)',
       '56.7 - 61.24kg (lightweight)', '56lb weight throw (25.4kg)',
       '61.23 - 65.77kg (lightweight)', '61.24 - 65.77kg (welterweight)',
       '65.77 - 71.67kg (middleweight)', '65.77 - 71.67kg (welterweight)',
       '880y freestyle (804.66m)', 'All-around dumbbell contest',
       'Club swinging', 'Combined 3 events', 'Combined 4 events',
       'Coxless pair (2-)', 'Decathlon',
       'Double american round (60y - 50y - 40y)',
       'Double columbia round (50y - 40y - 30y)',
       'Double national round (60y - 50y)', 'Double sculls (2x)',
       'Double york round (100y - 80y - 60y)', 'Foil team',
       'Four without coxswain (4-)', 'Lacrosse', 'Plunge for distance',
       'Stick, single', 'Team', 'Team competition', 'Team round 60y',
       'Teams fita round', 'Triathlon (long jump / shot put / 100 yards)',
       '+ 73kg (heavyweight)', '+ 93kg (super heavyweight)',
       '- 52.62kg (bantamweight)', '- 54kg (bantamweight)',
       '- 66.6kg (lightweight)', '1000y free rifle, prone',
       '100m running deer, double shots',
       '100m running deer, single shots',
       '100m running deer, single shots, team', '10miles walk (16093m)',
       '12m', '1980 yards pursuit, team', '2000m tandem',
       '200m breaststroke', '20km',
       '25y small bore rifle, disappearing target',
       '25y small bore rifle, moving target',
       '300m free rifle 3 positions (3x40 shots)', '3200m steeplechase',
       '3500m walk', '3m springboard', '3miles team (4828m)',
       '4x200m freestyle relay', '4x400m relay', '5 miles (8047m)',
       '50+100y small bore rifle, team', '5000m',
       '50m rifle prone (60 shots)', '50y army pistol, team',
       '52.62 - 57.15kg (featherweight)', '54 - 60.3kg (featherweight)',
       '57.15 - 63.5kg (lightweight)', '60.3 - 66.6kg (lightweight)',
       '63.5 - 71.67kg (middleweight)', '66.6 - 73kg (middleweight)',
       '6m', '73 - 93kg (light-heavyweight)', '7m', '8m', '8m class c',
       'One lap (660y) sprint', 'Class b up to 60 feet',
       'Clay pigeons, team', 'Continental style 50m',
       'Discus throw ancient style', 'Doubles indoor', 'Hockey',
       'Javelin throw', 'Javelin throw freestyle',
       'National round (60y - 50y)', 'Open class a', 'Pairs',
       'Rifle, team', 'Sabre team', 'Singles indoor', 'Special figures',
       'York round (100y - 80y - 60y)', 'Épée team',
       '+ 82.5kg (super heavyweight)', '- 60kg (featherweight)', '10000m',
       '10000m walk', '10m', '25m small bore rifle, team',
       '25m small rifle', '3000m team', '30m army pistol, team',
       '4x100m freestyle relay', '4x100m relay',
       '50m small bore rifle, team', '60 - 67.5kg (lightweight)',
       '600m free rifle', '67.5 - 75kg (middleweight)',
       '75 - 82.5kg (light-heavyweight)', 'Individual competition',
       'Coxed fours jugriggers', 'Cross country individual',
       'Cross country team', 'Discus throw, both hands',
       'Individual time trial', 'Javelin throw, both hands',
       'Mixed doubles indoor', 'Pentathlon', 'Plain high diving',
       'Shot put, both hands', 'Team time trial', 'Team, swedish system',
       'Team, free system', '+ 79.38kg (heavyweight)',
       '+ 80kg (heavyweight)',
       '+ 82.5kg, one-two hand 3 events (heavyweight)',
       '+ 82kg (super heavyweight)', '- 50.8kg (flyweight)',
       '- 60kg, one-two hand 3 events (featherweight)',
       '100m running deer, double shots, team', '10m (rating 1907)',
       '10m (rating 1919)', '12 foot dinghy', '12m (rating 1907)',
       '12m (rating 1919)', '18 foot dinghy',
       '300+600m free rifle, team, prone', '3000m walk',
       '300m free rifle, prone, team', '300m free rifle, standing, team',
       '30m sq', '40m sq', '50.8 - 53.52kg (bantamweight)', '50km',
       '50m small bore rifle, standing, individual',
       '53.52 - 57.15kg (featherweight)', '57.15 - 61.24kg (lightweight)',
       '6.5m (rating 1919)',
       '60 - 67.5kg, one-two hand 3 events (lightweight)',
       '600m free rifle, prone', '600m free rifle, team',
       '61.24 - 66.68kg (welterweight)', '66.68 - 72.57kg (middleweight)',
       '67.5 - 75kg, one-two hand 3 events (middleweight)',
       '6m (rating 1907)', '6m (rating 1919)',
       '72.57 - 79.38kg (light-heavyweight)',
       '75 - 80kg (light-heavyweight)',
       '75 - 82.5kg, one-two hand 3 e. (light-heavyweight)',
       '75 - 82kg (light-heavyweight)', '8m (rating 1907)',
       '8m (rating 1919)', 'Team pursuit (4000m)',
       'Figure riding individual', 'Figure riding team',
       'Fixed bird target large birds',
       'Fixed bird target large birds teams',
       'Fixed bird target small bird, teams',
       'Fixed bird target small birds', 'Ice hockey',
       'Moving bird target 28m teams', 'Moving bird target 33m teams',
       'Moving bird target 50m teams', 'Moving bird target, 28m',
       'Moving bird target, 33m', 'Moving bird target, 50m',
       '+ 82.5kg, one-two hand 5 events (heavyweight)',
       '+ 87kg (heavyweight)', '- 56kg (bantamweight)',
       '- 58kg (bantamweight)',
       '- 60kg, one-two hand 5 events (featherweight)',
       '400, 600, 800m free rifle, team', '56 - 61kg (featherweight)',
       '58 - 62kg (featherweight)',
       '60 - 67.5kg, one-two hand 5 events (lightweight)',
       '600m free rifle, individual', '61 - 66kg (lightweight)',
       '62 - 67.5kg (lightweight)', '66 - 72kg (welterweight)',
       '67.5 - 75kg, one-two hand 5 events (middleweight)',
       '72 - 79kg (middleweight)',
       '75 - 82.5kg, one-two hand 5 e. (light-heavyweight)',
       '79 - 87kg (light-heavyweight)', 'Sidehorse vault',
       'Olympic class monotype', '+ 82.5kg, total (heavyweight)',
       '- 60kg, total (featherweight)', '12 foot dinghy individual',
       '1km pursuit', '58 - 60kg (featherweight)',
       '60 - 67.5kg, total (lightweight)',
       '67.5 - 75kg, total (middleweight)',
       '75 - 82.5kg, total (light-heavyweight)',
       '+ 87kg (super heavyweight)', '50.8 - 54kg (bantamweight)',
       '50km walk', '54 - 57.15kg (featherweight)', '80m hurdles',
       'Floor exercises', 'Indian clubs', 'Tumbling',
       'Two-person keelboat open (star)', 'C-1 1000m (canoe single)',
       'C-2 10000m', 'C-2 1000m (canoe double)', 'K-1 10000m',
       'K-1 1000m (kayak single)', 'K-2 10000m',
       'K-2 1000m (kayak double)', 'Basketball', 'Folding k-1 10000m',
       'Folding k-2 10000m', 'Handball', '- 51kg (flyweight)',
       '- 52kg (flyweight)', '- 56kg, total (bantamweight)',
       '51 - 54kg (bantamweight)', '52 - 57kg (bantamweight)',
       '54 - 58kg (featherweight)', '56 - 60kg, total (featherweight)',
       '57 - 61kg (featherweight)', '57 - 63kg (featherweight)',
       '58 - 62kg (lightweight)', '61 - 67kg (lightweight)',
       '62 - 67kg (welterweight)', '63 - 67kg (lightweight)',
       '67 - 73kg (middleweight)', '67 - 73kg (welterweight)',
       '73 - 79kg (middleweight)', '73 - 80kg (light-heavyweight)',
       'C-1 10000m', 'K-1 500m (kayak single)', 'Dragon', 'Firefly class',
       'Swallow (golondrina)', '+ 81kg (heavyweight)',
       '+ 90kg, total (heavyweight)',
       '100m running deer, single/double shots', '5.5m',
       '50m rifle 3 positions (3x40 shots)', '54 - 57kg (featherweight)',
       '57 - 60kg (lightweight)', '60 - 63.5kg (light-welterweight)',
       '63.5 - 67kg (welterweight)', '67 - 71kg (light-middleweight)',
       '71-75kg', '75 - 81kg (light-heavyweight)',
       '82.5 - 90kg, total (middle-heavyweight)', 'Balance beam',
       'Single-handed dinghy (finn)', 'Team, portable apparatus',
       'Uneven bars', '100m butterfly', '200m butterfly', '20km walk',
       'Sharpie 12m2', '4x100m medley relay', 'K-1 4x500m',
       'K-2 500m (kayak double)', 'Flying dutchman',
       '+ 97kg (heavyweight)', '+ 97kg (super heavyweight)',
       '- 68kg (lightweight)', '400m individual medley',
       '63 - 70kg (lightweight)', '68 - 80kg (middleweight)',
       '70 - 78kg (welterweight)', '78 - 87kg (middleweight)',
       '87 - 97kg (light-heavyweight)', 'Individual pursuit',
       'K-4 1000m (kayak four)', 'Open category', 'Volleyball',
       '- 48kg (light-flyweight)', '100m breaststroke',
       '200m individual medley', '48 - 51kg (flyweight)',
       '800m freestyle', 'Skeet (125 targets)',
       '+ 100kg (super heavyweight)',
       '+ 110kg, total (super heavyweight)', '+ 93kg (heavyweight)',
       '- 52kg, total (flyweight)', '- 63kg (lightweight)',
       '100m hurdles', '48 - 52kg (flyweight)',
       '50m running target (30+30 shots)',
       '52 - 56kg, total (bantamweight)', '57 - 62kg (featherweight)',
       '62 - 68kg (lightweight)', '63 - 70kg (half-middleweight)',
       '68 - 74kg (welterweight)', '70 - 80kg (middleweight)',
       '74 - 82kg (middleweight)', '80 - 93kg (half-heavyweight)',
       '82 - 90kg (light-heavyweight)', '90 - 100kg (heavyweight)',
       '91 - 110kg, total (heavyweight)', 'C-1 (canoe single)',
       'C-2 (canoe double)', 'K-1 (kayak single)',
       'Fleet/match race keelboat open (soling)', 'Individual fita round',
       'Tempest', '470 - two person dinghy', 'C-1 500m (canoe single)',
       'C-2 500m (canoe double)', 'Tornado - multihull',
       'Pair without coxswain (2-)',
       'Quadruple sculls with coxswain (4x)',
       'Quadruple sculls without coxswain (4x)', '+ 95kg (heavyweight)',
       '- 60 kg', '100 - 110kg, total (heavyweight)',
       '60 - 65kg (half-lightweight)', '65 - 71kg (lightweight)',
       '71 - 78kg (half-middleweight)', '78 - 86kg (middleweight)',
       '86 - 95kg (half-heavyweight)',
       '90 - 100kg, total (first-heavyweight)',
       '+ 91kg (super heavyweight)', '10m air rifle (40 shots)',
       '10m air rifle (60 shots)', '25m pistol (30+30 shots)', '3000m',
       '50m rifle 3 positions (3x20 shots)', '81 - 91kg (heavyweight)',
       'K-4 500m (kayak four)', 'Points race', 'Board (windglider)',
       'Duet', 'Heptathlon', 'Solo', '100 - 130kg (super heavyweight)',
       '10m air pistol (40 shots)', '10m air pistol (60 shots)',
       '50m freestyle', 'Board (division ii)', 'Sprint',
       '+ 72kg (heavyweight)', '- 48kg (extra-lightweight)',
       '48 - 52kg (half-lightweight)', '52 - 56kg (lightweight)',
       '56 - 61kg (half-middleweight)', '61 - 66kg (middleweight)',
       '66 - 72kg (half-heavyweight)', 'Baseball', 'Board (lechner)',
       'Coxless four (4-)', 'Individual (fita olympic round - 70m)',
       'Single-handed dinghy (europe)', 'Team (fita olympic round - 70m)',
       '+ 100kg (heavyweight)', '+ 108kg, total (super heavyweight)',
       '- 54kg, total (flyweight)', '54 - 59kg, total (bantamweight)',
       '59 - 64kg, total (featherweight)', '60 - 66kg (half-lightweight)',
       '64 - 70kg, total (lightweight)', '66 - 73kg (lightweight)',
       '70 - 76kg, total (middleweight)', '73 - 81kg (half-middleweight)',
       '76 - 83kg, total (light-heavyweight)', '81 - 90kg (middleweight)',
       '83 - 91kg, total (middle-heavyweight)',
       '90 - 100kg (half-heavyweight)',
       '91 - 99kg, total (first-heavyweight)',
       '99 - 108kg, total (heavyweight)', 'Beach volleyball',
       'Board (mistral)', 'Cross-country', 'Double trap (120 targets)',
       'Double trap (150 targets)', 'Group competition',
       'Lightweight coxless four (4-)', 'Lightweight double sculls (2x)',
       'Single-handed dinghy open (laser)', 'Softball', '+ 105kg',
       '+ 67 kg', '+ 75kg', '+ 78kg (heavyweight)', '+ 80 kg', '- 49 kg',
       '- 58 kg', '105kg', '10m running target (30+30 shots)',
       '20km race walk', '48 - 54kg', '48kg', '49 - 57 kg',
       '49er - skiff', '500m time trial', '52 - 57kg (lightweight)',
       '53kg', '54 - 58kg', '56kg', '57 - 63kg (half-middleweight)',
       '57 - 67 kg', '58 - 63kg', '58 - 68 kg', '58kg', '62kg',
       '63 - 69kg', '63 - 70kg (middleweight)', '63kg', '68 - 80 kg',
       '69 - 76kg', '69kg', '70 - 78kg (half-heavyweight)', '75kg',
       '76 - 85kg', '77kg', '85 - 97kg', '85kg', '94kg', '97 - 130kg',
       'Keirin', 'Madison', 'Olympic sprint', 'Skeet (75 targets)',
       'Synchronized diving 10m platform',
       'Synchronized diving 3m springboard', 'Trap (75 targets)',
       '- 48 kg', '- 48kg', '- 55kg', '48 - 55kg',
       '48kg (light flywieght)', '55 - 60kg', '55 - 63kg', '60 - 64 kg',
       '60 - 66kg', '63 - 72kg', '64 - 69 kg', '66 - 74kg', '69 - 75 kg',
       '74 - 84kg', '84 - 96kg', '96 - 120kg', 'Star - keelboat',
       'Team sprint', 'Yngling - keelboat'], dtype=object)

In [26]:
dir(oo.Event.str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'removeprefix',
 'removesuffix',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']

In [28]:
oo["Athlete Name"].str.contains("Latynina")

0        False
1        False
2        False
3        False
4        False
         ...
27169    False
27170    False
27171    False
27172    False
27173    False
Name: Athlete Name, Length: 27174, dtype: bool

In [29]:
# Larisa Latynina - most decorated Female athlete
oo[oo["Athlete Name"].str.contains("Latynina")]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

Empty DataFrame
Columns: [Year, City, Sport, Discipline, Athlete Name, NOC, Gender, Event, Event Gender, Medal]
Index: []

In [30]:
oo[oo["Athlete Name"].str.contains("LATYNINA")]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
9372,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Floor exercises,W,Gold
9539,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Individual all-round,W,Gold
9679,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Team competition,W,Gold
9702,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,"Team, portable apparatus",W,Bronze
9735,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Uneven bars,W,Silver
9741,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Vault,W,Gold
10179,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Balance beam,W,Silver
10277,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Floor exercises,W,Gold
10458,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Individual all-round,W,Gold
10576,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Team competition,W,Gold
10612,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Uneven bars,W,Silver
10616,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Vault,W,Bronze
11095,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Balance beam,W,Bronze
11195,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Floor exercises,W,Gold
11387,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Individual all-round,W,Silver
11517,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Team competition,W,Gold
11551,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Uneven bars,W,Bronze
11558,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,Vault,W,Silver

In [31]:
dir(oo.Event.str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'removeprefix',
 'removesuffix',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']

In [32]:
oo.City = oo.City.str.upper()
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
26273,2004,ATHENS,Football,Football,"PELIZZOLI, Ivan",ITA,Men,Football,M,Bronze
8905,1952,HELSINKI,Fencing,Fencing,"MAGNUSSON, Lennart",SWE,Men,Épée team,M,Silver
1511,1908,LONDON,Football,Football,"BUCHWALD, Charles",DEN,Men,Football,M,Silver

In [33]:
oo.City.unique()

array(['ATHENS', 'PARIS', 'ST LOUIS', 'LONDON', 'STOCKHOLM', 'ANTWERP',
       'AMSTERDAM', 'LOS ANGELES', 'BERLIN', 'HELSINKI',
       'MELBOURNE / STOCKHOLM', 'ROME', 'TOKYO', 'MEXICO', 'MUNICH',
       'MONTREAL', 'MOSCOW', 'SEOUL', 'BARCELONA', 'ATLANTA', 'SYDNEY'],
      dtype=object)

## Sorting a DataFrame or Series

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

In [34]:
oo["Athlete Name"].sort_values()

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

611                 AABYE, Edgar
3060       AALTONEN, Arvo Ossian
2963       AALTONEN, Arvo Ossian
7792    AALTONEN, Paavo Johannes
7906    AALTONEN, Paavo Johannes
                  ...
275                   ÖSTMO, Ole
443                   ÖSTMO, Ole
280                   ÖSTMO, Ole
268                   ÖSTMO, Ole
8125           ÖSTRAND, Per-Olof
Name: Athlete Name, Length: 27174, dtype: object

In [35]:
type(oo["Athlete Name"].sort_values())

pandas.core.series.Series

In [36]:
oo.sort_values("Athlete Name")

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
611,1900,PARIS,Tug of War,Tug of War,"AABYE, Edgar",ZZX,Men,Tug of war,M,Gold
3060,1920,ANTWERP,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,400m breaststroke,M,Bronze
2963,1920,ANTWERP,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,200m breaststroke,M,Bronze
7792,1948,LONDON,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Individual all-round,M,Bronze
7906,1948,LONDON,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Team competition,M,Gold
...,...,...,...,...,...,...,...,...,...,...
275,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, prone",M,Bronze
443,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Free rifle, team",M,Silver
280,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, standing",M,Silver
268,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, 3 positions",M,Bronze
8125,1952,HELSINKI,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400m freestyle,M,Bronze

In [37]:
type(oo.sort_values("Athlete Name"))

pandas.core.frame.DataFrame

In [38]:
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,ATHENS,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,ATHENS,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,ATHENS,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze

In [39]:
oo.sort_values("Athlete Name", ascending=False)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
8125,1952,HELSINKI,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400m freestyle,M,Bronze
268,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, 3 positions",M,Bronze
443,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Free rifle, team",M,Silver
275,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, prone",M,Bronze
280,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, standing",M,Silver
...,...,...,...,...,...,...,...,...,...,...
7967,1948,LONDON,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Vault,M,Gold
7792,1948,LONDON,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Individual all-round,M,Bronze
2963,1920,ANTWERP,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,200m breaststroke,M,Bronze
3060,1920,ANTWERP,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,400m breaststroke,M,Bronze
611,1900,PARIS,Tug of War,Tug of War,"AABYE, Edgar",ZZX,Men,Tug of war,M,Gold

In [40]:
oo.sort_values("Athlete Name", ascending=False).head(25)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
8125,1952,HELSINKI,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400m freestyle,M,Bronze
268,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, 3 positions",M,Bronze
443,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Free rifle, team",M,Silver
275,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, prone",M,Bronze
280,1900,PARIS,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army rifle, 300m, standing",M,Silver
2936,1920,ANTWERP,Sailing,Sailing,"ÖSTERVOLD, Ole Olsen",NOR,Men,12m (rating 1907),X,Gold
2935,1920,ANTWERP,Sailing,Sailing,"ÖSTERVOLD, Kristian Olsen",NOR,Men,12m (rating 1907),X,Gold
2934,1920,ANTWERP,Sailing,Sailing,"ÖSTERVOLD, Jan Olsen",NOR,Men,12m (rating 1907),X,Gold
2933,1920,ANTWERP,Sailing,Sailing,"ÖSTERVOLD, Henrik",NOR,Men,12m (rating 1907),X,Gold
2390,1912,STOCKHOLM,Shooting,Shooting,"ÖSTENSEN, Östen",NOR,Men,"Free rifle, team",M,Silver
2999,1920,ANTWERP,Shooting,Shooting,"ÖSTENSEN, Östen",NOR,Men,300m free rifle 3 positions (3x40 shots),M,Bronze
3161,1920,ANTWERP,Shooting,Shooting,"ÖSTENSEN, Östen",NOR,Men,"50m small bore rifle, team",M,Bronze
2982,1920,ANTWERP,Shooting,Shooting,"ÖSTENSEN, Östen",NOR,Men,"300+600m free rifle, team, prone",M,Silver
3526,1920,ANTWERP,Shooting,Shooting,"ÖSTENSEN, Östen",NOR,Men,"Free rifle, team",M,Silver
2943,1920,ANTWERP,Sailing,Sailing,"ÖRVIG, Thor",NOR,Men,12m (rating 1919),X,Gold
2942,1920,ANTWERP,Sailing,Sailing,"ÖRVIG, Olav",NOR,Men,12m (rating 1919),X,Gold
2941,1920,ANTWERP,Sailing,Sailing,"ÖRVIG, Erik",NOR,Men,12m (rating 1919),X,Gold
2185,1912,STOCKHOLM,Shooting,Shooting,"ÖRTEGREN, Ruben",SWE,Men,"50m small bore rifle, team",M,Silver
15637,1980,MOSCOW,Cycling,Cycling Track,"ÖRSTED, Hans-Henrik",DEN,Men,Individual pursuit,M,Bronze
2003,1912,STOCKHOLM,Aquatics,Diving,"ZÜRNER, Albert",GER,Men,10m platform,M,Silver
1259,1908,LONDON,Aquatics,Diving,"ZÜRNER, Albert",GER,Men,3m springboard,M,Gold
18424,1988,SEOUL,Boxing,Boxing,"ZÜLOW, Andreas",GDR,Men,57 - 60kg (lightweight),M,Gold
19265,1988,SEOUL,Rowing,Rowing,"ZÜHLKE, Steffen",GDR,Men,Quadruple sculls without coxswain (4x),M,Bronze
10013,1960,ROME,Shooting,Shooting,"ZÄHRINGER, Klaus",EUA,Men,50m rifle 3 positions (3x40 shots),M,Bronze
25587,2004,ATHENS,Athletics,Athletics,"ZYKINA, Olesya",RUS,Women,4x400m relay,W,Silver

In [41]:
oo.sort_values(by=['Year','Athlete Name'])

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
20,1896,ATHENS,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
103,1896,ATHENS,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,Rope climbing,M,Gold
141,1896,ATHENS,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"Team, parallel bars",M,Silver
142,1896,ATHENS,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"Team, parallel bars",M,Silver
79,1896,ATHENS,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,Individual road race,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
25753,2004,ATHENS,Boxing,Boxing,"ZUYEV, Viktar",BLR,Men,81 - 91kg (heavyweight),M,Silver
25748,2004,ATHENS,Judo,Judo,"ZVIADAURI, Zurab",GEO,Men,81 - 90kg (middleweight),M,Gold
26570,2004,ATHENS,Hockey,Hockey,"ZWEHL, Julia",GER,Women,Hockey,W,Gold
25440,2004,ATHENS,Aquatics,Swimming,"ZWERING, Klaas-Erik",NED,Men,4x100m freestyle relay,M,Silver
25587,2004,ATHENS,Athletics,Athletics,"ZYKINA, Olesya",RUS,Women,4x400m relay,W,Silver

In [42]:
oo.sort_values(by=["Year", "Athlete Name"], ascending=[False, True])

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
25212,2004,ATHENS,Wrestling,Wrestling Free.,"ABAS, Stephen",USA,Men,- 55kg,M,Silver
26832,2004,ATHENS,Cycling,Cycling Track,"ABASSOVA, Tamilla",RUS,Women,Sprint,W,Silver
25418,2004,ATHENS,Taekwondo,Taekwondo,"ABDALLAH, Nia",USA,Women,49 - 57 kg,W,Silver
25726,2004,ATHENS,Wrestling,Wrestling Gre-R,"ABRAHAMIAN, Ara",SWE,Men,74 - 84kg,M,Silver
26997,2004,ATHENS,Volleyball,Volleyball,"ABRAMOV, Pavel",RUS,Men,Volleyball,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
104,1896,ATHENS,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,Rope climbing,M,Silver
144,1896,ATHENS,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,"Team, parallel bars",M,Silver
92,1896,ATHENS,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,Parallel bars,M,Silver
97,1896,ATHENS,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,Pommel horse,M,Gold
150,1896,ATHENS,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,Vault,M,Silver

In [43]:
oo.head(7)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,ATHENS,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,ATHENS,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,ATHENS,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,ATHENS,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,ATHENS,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
5,1896,ATHENS,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
6,1896,ATHENS,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold

In [44]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
1,1896,ATHENS,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
0,1896,ATHENS,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
5,1896,ATHENS,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
4,1896,ATHENS,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
2,1896,ATHENS,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,ATHENS,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
7,1896,ATHENS,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver

In [45]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year             int64
City            object
Sport           object
Discipline      object
Athlete Name    object
NOC             object
Gender          object
Event           object
Event Gender    object
Medal           object
dtype: object

## Working with data types (dtype)

In [46]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

Installed all of the necessary files for this section ...

In [47]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
5911,1932,Los Angeles,Boxing,Boxing,"CAMPE, Erich",GER,Men,61.24 - 66.68kg (welterweight),M,Silver
13766,1972,Munich,Sailing,Sailing,"FORBES, David John Oliver",AUS,Men,two-person keelboat open (Star),X,Gold
3039,1920,Antwerp,Shooting,Shooting,"KELLY, Michael",USA,Men,"30m army pistol, team",M,Gold

In [48]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year             int64
City            object
Sport           object
Discipline      object
Athlete Name    object
NOC             object
Gender          object
Event           object
Event Gender    object
Medal           object
dtype: object

In [49]:
oo.Medal.unique()

array(['Gold', 'Silver', 'Bronze'], dtype=object)

In [50]:
oo.Medal = oo.Medal.astype("category")
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year               int64
City              object
Sport             object
Discipline        object
Athlete Name      object
NOC               object
Gender            object
Event             object
Event Gender      object
Medal           category
dtype: object

In [51]:
oo.Gender.unique()

array(['Men', 'Women'], dtype=object)

In [ ]:
oo['Event Gender'].unique()

In [52]:
oo.Gender = oo.Gender.astype("category")
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year               int64
City              object
Sport             object
Discipline        object
Athlete Name      object
NOC               object
Gender          category
Event             object
Event Gender    category
Medal           category
dtype: object

In [53]:
oo.Medal.astype("category")

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

0          Gold
1        Silver
2        Bronze
3        Bronze
4          Gold
          ...
27169      Gold
27170      Gold
27171    Silver
27172    Silver
27173    Silver
Name: Medal, Length: 27174, dtype: category
Categories (3, object): ['Bronze', 'Gold', 'Silver']

In [54]:
pd.Categorical?

In [55]:
medal_order = ["Bronze", "Silver", "Gold"]
pd.Categorical(oo.Medal, categories=medal_order, ordered=True)

['Gold', 'Silver', 'Bronze', 'Bronze', 'Gold', ..., 'Gold', 'Gold', 'Silver', 'Silver', 'Silver']
Length: 27174
Categories (3, object): ['Bronze' < 'Silver' < 'Gold']

In [56]:
oo.Medal = pd.Categorical(oo.Medal, categories=medal_order, ordered=True)
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year               int64
City              object
Sport             object
Discipline        object
Athlete Name      object
NOC               object
Gender          category
Event             object
Event Gender    category
Medal           category
dtype: object

In [57]:
oo.Medal

0          Gold
1        Silver
2        Bronze
3        Bronze
4          Gold
          ...
27169      Gold
27170      Gold
27171    Silver
27172    Silver
27173    Silver
Name: Medal, Length: 27174, dtype: category
Categories (3, object): ['Bronze' < 'Silver' < 'Gold']

In [58]:
oo.sort_values(by=["Year", "Event", "Medal"], ascending=[True, True, False]).head(7)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
6,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold

## Memory usage of different dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [60]:
df = pd.read_csv(filename, skiprows=5)
df.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year             int64
City            object
Sport           object
Discipline      object
Athlete Name    object
NOC             object
Gender          object
Event           object
Event Gender    object
Medal           object
Position         int64
dtype: object

In [61]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year               int64
City              object
Sport             object
Discipline        object
Athlete Name      object
NOC               object
Gender          category
Event             object
Event Gender    category
Medal           category
dtype: object

In [62]:
oo.Medal.memory_usage?

In [63]:
print(f"Medal series memory usage using dtype category: {oo.Medal.memory_usage(deep=True)}")
print(f"Medal series memory usage using dtype object: {df.Medal.memory_usage(deep=True)}")

Medal series memory usage using dtype category: 27601
Medal series memory usage using dtype object: 1693732

In [64]:
oo.Medal.memory_usage(deep=True) / df.Medal.memory_usage(deep=True)

0.01629596654016102

In [65]:
print(f"Gender series memory usage using dtype category: {oo.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df.Gender.memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype category: {oo['Event Gender'].memory_usage(deep=True)}")
print(f"Gender series memory usage using dtype object: {df['Event Gender'].memory_usage(deep=True)}")

Gender series memory usage using dtype category: 27536
Gender series memory usage using dtype object: 1643698
Gender series memory usage using dtype category: 27588
Gender series memory usage using dtype object: 1576224

In [66]:
oo.City.astype("string")

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

0        Athens
1        Athens
2        Athens
3        Athens
4        Athens
          ...
27169    Athens
27170    Athens
27171    Athens
27172    Athens
27173    Athens
Name: City, Length: 27174, dtype: string

In [67]:
oo.sample(2)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
25948,2004,Athens,Baseball,Baseball,"KIMURA, Takuya",JPN,Men,baseball,M,Bronze
5024,1928,Amsterdam,Wrestling,Wrestling Gre-R,"MAUDR, Jindrich",TCH,Men,- 58kg (bantamweight),M,Silver

In [ ]:
oo.dtypes

In [68]:
oo.City = oo.City.astype("string")
oo.Sport = oo.Sport.astype("string")
oo.Discipline = oo.Discipline.astype("string")
oo["Athlete Name"] = oo["Athlete Name"].astype("string")
oo.NOC = oo.NOC.astype("string")
oo.Event = oo.Event.astype("string")
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender          category
Medal                 category
dtype: object

In [69]:
oo.City.dtype

string[python]

In [70]:
df.City.dtype

dtype('O')

In [71]:
print(f"City series memory usage using dtype string: {oo.City.memory_usage(deep=True)}")
print(f"City series memory usage using dtype object: {df.City.memory_usage(deep=True)}")

City series memory usage using dtype string: 1748408
City series memory usage using dtype object: 1748408

## Defining dtypes when you read in a file

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [72]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
22387,1996,Atlanta,Football,Football,"OVERBECK, Carla",USA,Women,football,W,Gold
11759,1968,Mexico,Cycling,Cycling Track,"TRENTIN, Pierre",FRA,Men,1km time trial,M,Gold
253,1900,Paris,Shooting,Shooting,"MOREAUX, Léon",FRA,Men,"50m army pistol, team",M,Silver

In [73]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year             int64
City            object
Sport           object
Discipline      object
Athlete Name    object
NOC             object
Gender          object
Event           object
Event Gender    object
Medal           object
dtype: object

In [74]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": "category"}

dtype_mapper

{'Year': 'int64',
 'City': 'string',
 'Sport': 'string',
 'Discipline': 'string',
 'Athlete Name': 'string',
 'NOC': 'string',
 'Gender': 'category',
 'Event': 'string',
 'Event_gender': 'category',
 'Medal': 'category'}

In [75]:
pd.api.types.CategoricalDtype?

In [76]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
ordered_medals

CategoricalDtype(categories=['Bronze', 'Silver', 'Gold'], ordered=True, categories_dtype=object)

In [77]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

{'Year': 'int64',
 'City': 'string',
 'Sport': 'string',
 'Discipline': 'string',
 'Athlete Name': 'string',
 'NOC': 'string',
 'Gender': 'category',
 'Event': 'string',
 'Event_gender': 'category',
 'Medal': CategoricalDtype(categories=['Bronze', 'Silver', 'Gold'], ordered=True, categories_dtype=object)}

In [78]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
4536,1924,Paris,Rowing,Rowing,"GALLASSO, Latino",ITA,Men,eight with coxswain (8+),M,Bronze,3
5133,1928,Amsterdam,Athletics,Athletics,"HOLDMANN, Anny",GER,Women,4x100m relay,W,Bronze,3
12230,1968,Mexico,Gymnastics,Artistic G.,"CASLAVSKA, Vera",TCH,Women,floor exercises,W,Gold,1

In [79]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender            object
Medal                 category
Position                 int64
dtype: object

In [80]:
oo["Event Gender"].unique()

array(['M', 'X', 'W'], dtype=object)

In [81]:
oo = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
oo['Event Gender'] = oo['Event Gender'].astype("category")
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender          category
Medal                 category
Position                 int64
dtype: object

## Python Functions

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [82]:
def show_df(filename="olympics_1896_2004.csv"):
  """Read in csv file and display DataFrame"""
  df = pd.read_csv(filename, skiprows=5)
  return df

show_df()

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [83]:
type(show_df())

pandas.core.frame.DataFrame

In [84]:
ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}

dtype_mapper

{'Year': 'int64',
 'City': 'string',
 'Sport': 'string',
 'Discipline': 'string',
 'Athlete Name': 'string',
 'NOC': 'string',
 'Gender': 'category',
 'Event': 'string',
 'Event_gender': 'category',
 'Medal': CategoricalDtype(categories=['Bronze', 'Silver', 'Gold'], ordered=True, categories_dtype=object)}

In [85]:
oo = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
      .drop('Position', axis=1)
)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
8608,1952,Helsinki,Hockey,Hockey,"DALUZ, Meldric St.Clair",IND,Men,hockey,M,Gold
14670,1976,Montreal,Rowing,Rowing,"FRICKE, Siegfried",FRG,Men,four-oared shell with coxswain (4-),M,Bronze
15409,1980,Moscow,Aquatics,Swimming,"KRUGLOVA, Elena",URS,Women,4x100m medley relay,W,Bronze

In [86]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )

  return df

preprocess()

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [ ]:
preprocess()

In [87]:
oo = preprocess()
oo.sample(3)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
945,1904,St Louis,Rowing,Rowing,"DIETZ, George",USA,Men,four without coxswain (4-),M,Gold
6649,1936,Berlin,Cycling,Cycling Track,"RIGONI, Severino",ITA,Men,Team Pursuit (4000m),M,Silver
16931,1984,Los Angeles,Wrestling,Wrestling Gre-R,"ETO, Masaki",JPN,Men,52 - 57kg (bantamweight),M,Silver

In [88]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender            object
Medal                 category
dtype: object

In [ ]:
oo["Event Gender"].unique()

In [90]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
4584,1924,Paris,Football,Football,"ALFREDSSON, Axel",SWE,Men,football,M,Bronze
11845,1968,Mexico,Boxing,Boxing,"OLECH, Artur",POL,Men,48 - 51kg (flyweight),M,Silver
8703,1952,Helsinki,Fencing,Fencing,"PAPP, Bertalan",HUN,Men,sabre team,M,Gold

In [91]:
oo.dtypes

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender          category
Medal                 category
dtype: object

## Working with Indexes

In [92]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

Installed all of the necessary files for this section ...

In [93]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.head(5)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold

In [94]:
oo.index

RangeIndex(start=0, stop=27174, step=1)

In [95]:
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'],
      dtype='object')

In [96]:
oo.shape

(27174, 10)

In [97]:
pd.read_csv(filename, skiprows=5, header=None).head()

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,0,1,2,3,4,5,6,7,8,9,10
0,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
1,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
2,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
3,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3

In [98]:
oo = preprocess()
oo.head(5)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold

In [99]:
oo[oo['Athlete Name'].str.contains("LEWIS, Carl")]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
16636,1984,Los Angeles,Athletics,Athletics,"LEWIS, Carl",USA,Men,100m,M,Gold
16697,1984,Los Angeles,Athletics,Athletics,"LEWIS, Carl",USA,Men,200m,M,Gold
16847,1984,Los Angeles,Athletics,Athletics,"LEWIS, Carl",USA,Men,4x100m relay,M,Gold
17709,1984,Los Angeles,Athletics,Athletics,"LEWIS, Carl",USA,Men,long jump,M,Gold
18098,1988,Seoul,Athletics,Athletics,"LEWIS, Carl",USA,Men,100m,M,Gold
18165,1988,Seoul,Athletics,Athletics,"LEWIS, Carl",USA,Men,200m,M,Silver
19227,1988,Seoul,Athletics,Athletics,"LEWIS, Carl",USA,Men,long jump,M,Gold
19908,1992,Barcelona,Athletics,Athletics,"LEWIS, Carl",USA,Men,4x100m relay,M,Gold
20917,1992,Barcelona,Athletics,Athletics,"LEWIS, Carl",USA,Men,long jump,M,Gold
22719,1996,Atlanta,Athletics,Athletics,"LEWIS, Carl",USA,Men,long jump,M,Gold

In [100]:
oo.loc[22719, "Event"]

'long jump'

In [101]:
oo = oo.set_index("Athlete Name")
oo.head(5)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"FLAMENG, Léon",1896,Athens,Cycling,Cycling Track,FRA,Men,100km,M,Gold
"KOLETTIS, Georgios",1896,Athens,Cycling,Cycling Track,GRE,Men,100km,M,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100m,M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100m,M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100m,M,Gold

In [102]:
oo.index

Index(['FLAMENG, Léon', 'KOLETTIS, Georgios', 'LANE, Francis',
       'SZOKOLYI, Alajos', 'BURKE, Thomas', 'HOFMANN, Fritz', 'HAJOS, Alfred',
       'HERSCHMANN, Otto', 'DRIVAS, Dimitrios', 'MALOKINIS, Ioannis',
       ...
       'FLESSEL-COLOVIC, Laura', 'KIRALY PICOT, Hajnalka', 'NISIMA, Maureen',
       'AZNAVOURIAN, Karina', 'ERMAKOVA, Oxana', 'LOGOUNOVA, Tatiana',
       'SIVKOVA, Anna', 'BOKEL, Claudia', 'DUPLITZER, Imke',
       'HEIDEMANN, Britta'],
      dtype='string', name='Athlete Name', length=27174)

In [103]:
oo.loc["LEWIS, Carl", "Event"]

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Athlete Name
LEWIS, Carl            100m
LEWIS, Carl            200m
LEWIS, Carl    4x100m relay
LEWIS, Carl       long jump
LEWIS, Carl            100m
LEWIS, Carl            200m
LEWIS, Carl       long jump
LEWIS, Carl    4x100m relay
LEWIS, Carl       long jump
LEWIS, Carl       long jump
Name: Event, dtype: string

In [104]:
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"FLAMENG, Léon",1896,Athens,Cycling,Cycling Track,FRA,Men,100km,M,Gold
"KOLETTIS, Georgios",1896,Athens,Cycling,Cycling Track,GRE,Men,100km,M,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100m,M,Bronze

In [105]:
oo.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'NOC', 'Gender', 'Event',
       'Event Gender', 'Medal'],
      dtype='object')

In [106]:
oo.shape

(27174, 9)

In [107]:
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"FLAMENG, Léon",1896,Athens,Cycling,Cycling Track,FRA,Men,100km,M,Gold
"KOLETTIS, Georgios",1896,Athens,Cycling,Cycling Track,GRE,Men,100km,M,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100m,M,Bronze

In [108]:
oo.loc["LEWIS, Carl", ["Year", "Event", "Medal"]]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

              Year         Event   Medal
Athlete Name
LEWIS, Carl   1984          100m    Gold
LEWIS, Carl   1984          200m    Gold
LEWIS, Carl   1984  4x100m relay    Gold
LEWIS, Carl   1984     long jump    Gold
LEWIS, Carl   1988          100m    Gold
LEWIS, Carl   1988          200m  Silver
LEWIS, Carl   1988     long jump    Gold
LEWIS, Carl   1992  4x100m relay    Gold
LEWIS, Carl   1992     long jump    Gold
LEWIS, Carl   1996     long jump    Gold

In [109]:
oo.loc["LEWIS, Carl", :]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,100m,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,200m,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,4x100m relay,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,100m,M,Gold
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,200m,M,Silver
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1992,Barcelona,Athletics,Athletics,USA,Men,4x100m relay,M,Gold
"LEWIS, Carl",1992,Barcelona,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1996,Atlanta,Athletics,Athletics,USA,Men,long jump,M,Gold

In [110]:
oo.loc["LEWIS, Carl"]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,100m,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,200m,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,4x100m relay,M,Gold
"LEWIS, Carl",1984,Los Angeles,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,100m,M,Gold
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,200m,M,Silver
"LEWIS, Carl",1988,Seoul,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1992,Barcelona,Athletics,Athletics,USA,Men,4x100m relay,M,Gold
"LEWIS, Carl",1992,Barcelona,Athletics,Athletics,USA,Men,long jump,M,Gold
"LEWIS, Carl",1996,Atlanta,Athletics,Athletics,USA,Men,long jump,M,Gold

In [111]:
oo = oo.sort_index()
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
Athlete Name,,,,,,,,,
"AABYE, Edgar",1900,Paris,Tug of War,Tug of War,ZZX,Men,tug of war,M,Gold
"AALTONEN, Arvo Ossian",1920,Antwerp,Aquatics,Swimming,FIN,Men,400m breaststroke,M,Bronze
"AALTONEN, Arvo Ossian",1920,Antwerp,Aquatics,Swimming,FIN,Men,200m breaststroke,M,Bronze

In [112]:
oo = oo.reset_index()
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Athlete Name,Year,City,Sport,Discipline,NOC,Gender,Event,Event Gender,Medal
0,"AABYE, Edgar",1900,Paris,Tug of War,Tug of War,ZZX,Men,tug of war,M,Gold
1,"AALTONEN, Arvo Ossian",1920,Antwerp,Aquatics,Swimming,FIN,Men,400m breaststroke,M,Bronze
2,"AALTONEN, Arvo Ossian",1920,Antwerp,Aquatics,Swimming,FIN,Men,200m breaststroke,M,Bronze

In [113]:
oo.iloc[0, 0]

'AABYE, Edgar'

In [115]:
oo.iloc[0, 5]

'ZZX'

In [116]:
oo.iloc[0, :]

/usr/local/lib/python3.11/dist-packages/google/colab/_reprs.py:211: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  series_as_table_html = series.to_frame()._repr_html_()  # pylint: disable=protected-access

Athlete Name    AABYE, Edgar
Year                    1900
City                   Paris
Sport             Tug of War
Discipline        Tug of War
NOC                      ZZX
Gender                   Men
Event             tug of war
Event Gender               M
Medal                   Gold
Name: 0, dtype: object

In [117]:
oo.iloc[0]

Athlete Name    AABYE, Edgar
Year                    1900
City                   Paris
Sport             Tug of War
Discipline        Tug of War
NOC                      ZZX
Gender                   Men
Event             tug of war
Event Gender               M
Medal                   Gold
Name: 0, dtype: object

## Being Productive in pandas - My Best Practices

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [118]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()
oo.sample(3)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
15281,1980,Moscow,Aquatics,Diving,"AMBARTSUMYAN, David",URS,Men,10m platform,M,Bronze
14288,1976,Montreal,Weightlifting,Weightlifting,"SHOPOV, Atanas",BUL,Men,"82.5 - 90kg, total (middle-heavyweight)",M,Bronze
9522,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"ONO, Takashi",JPN,Men,horizontal bar,M,Gold

**Get immediate feedback**

In [ ]:
oo = preprocess()

In [119]:
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
24611,2000,Sydney,Archery,Archery,"WUNDERLE, Victor",USA,Men,individual (FITA Olympic round - 70m),M,Silver
14635,1976,Montreal,Football,Football,"RIEDEL, Dieter",GDR,Men,football,M,Gold
8722,1952,Helsinki,Sailing,Sailing,"CURREY, Charles Norman",GBR,Men,single-handed dinghy (Finn),M,Silver

In [120]:
oo = preprocess()
oo.sample(3)

Preprocessing olympics_1896_2004.csv ...

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
11930,1968,Mexico,Athletics,Athletics,"HENNIGE, Gerhard",FRG,Men,4x400m relay,M,Bronze
9230,1956,Melbourne / Stockholm,Canoe / Kayak,Canoe / Kayak F,"PISSAREV, Igor",URS,Men,K-1 1000m (kayak single),M,Silver
1222,1908,London,Cycling,Cycling Track,"PAYNE, Ernest",GBR,Men,"1980 yards Pursuit, Team",M,Gold

**Understand the basics of Python**

In [121]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [122]:
[func.upper() for func in dir(pd)]

['ARROWDTYPE',
 'BOOLEANDTYPE',
 'CATEGORICAL',
 'CATEGORICALDTYPE',
 'CATEGORICALINDEX',
 'DATAFRAME',
 'DATEOFFSET',
 'DATETIMEINDEX',
 'DATETIMETZDTYPE',
 'EXCELFILE',
 'EXCELWRITER',
 'FLAGS',
 'FLOAT32DTYPE',
 'FLOAT64DTYPE',
 'GROUPER',
 'HDFSTORE',
 'INDEX',
 'INDEXSLICE',
 'INT16DTYPE',
 'INT32DTYPE',
 'INT64DTYPE',
 'INT8DTYPE',
 'INTERVAL',
 'INTERVALDTYPE',
 'INTERVALINDEX',
 'MULTIINDEX',
 'NA',
 'NAT',
 'NAMEDAGG',
 'PERIOD',
 'PERIODDTYPE',
 'PERIODINDEX',
 'RANGEINDEX',
 'SERIES',
 'SPARSEDTYPE',
 'STRINGDTYPE',
 'TIMEDELTA',
 'TIMEDELTAINDEX',
 'TIMESTAMP',
 'UINT16DTYPE',
 'UINT32DTYPE',
 'UINT64DTYPE',
 'UINT8DTYPE',
 '__ALL__',
 '__BUILTINS__',
 '__CACHED__',
 '__DOC__',
 '__DOCFORMAT__',
 '__FILE__',
 '__GIT_VERSION__',
 '__LOADER__',
 '__NAME__',
 '__PACKAGE__',
 '__PATH__',
 '__SPEC__',
 '__VERSION__',
 '_BUILT_WITH_MESON',
 '_CONFIG',
 '_IS_NUMPY_DEV',
 '_LIBS',
 '_PANDAS_DATETIME_CAPI',
 '_PANDAS_PARSER_CAPI',
 '_TESTING',
 '_TYPING',
 '_VERSION_MESON',
 'ANNOTATIONS',
 'API',
 'ARRAY',
 'ARRAYS',
 'BDATE_RANGE',
 'COMPAT',
 'CONCAT',
 'CORE',
 'CROSSTAB',
 'CUT',
 'DATE_RANGE',
 'DESCRIBE_OPTION',
 'ERRORS',
 'EVAL',
 'FACTORIZE',
 'FROM_DUMMIES',
 'GET_DUMMIES',
 'GET_OPTION',
 'INFER_FREQ',
 'INTERVAL_RANGE',
 'IO',
 'ISNA',
 'ISNULL',
 'JSON_NORMALIZE',
 'LRESHAPE',
 'MELT',
 'MERGE',
 'MERGE_ASOF',
 'MERGE_ORDERED',
 'NOTNA',
 'NOTNULL',
 'OFFSETS',
 'OPTION_CONTEXT',
 'OPTIONS',
 'PANDAS',
 'PERIOD_RANGE',
 'PIVOT',
 'PIVOT_TABLE',
 'PLOTTING',
 'QCUT',
 'READ_CLIPBOARD',
 'READ_CSV',
 'READ_EXCEL',
 'READ_FEATHER',
 'READ_FWF',
 'READ_GBQ',
 'READ_HDF',
 'READ_HTML',
 'READ_JSON',
 'READ_ORC',
 'READ_PARQUET',
 'READ_PICKLE',
 'READ_SAS',
 'READ_SPSS',
 'READ_SQL',
 'READ_SQL_QUERY',
 'READ_SQL_TABLE',
 'READ_STATA',
 'READ_TABLE',
 'READ_XML',
 'RESET_OPTION',
 'SET_ENG_FLOAT_FORMAT',
 'SET_OPTION',
 'SHOW_VERSIONS',
 'TEST',
 'TESTING',
 'TIMEDELTA_RANGE',
 'TO_DATETIME',
 'TO_NUMERIC',
 'TO_PICKLE',
 'TO_TIMEDELTA',
 'TSERIES',
 'UNIQUE',
 'UTIL',
 'VALUE_COUNTS',
 'WIDE_TO_LONG']

**Searching for method names**

In [123]:
import re
import pandas as pd

search_string = "excel"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

['ExcelFile', 'ExcelWriter', 'read_excel']

In [124]:
pd.read_excel?

In [125]:
[func
 for func in dir(pd)
 if re.search(rf"{search_string}", func, re.IGNORECASE)]

['ExcelFile', 'ExcelWriter', 'read_excel']

**Documentation while staying in the IDE**

In [127]:
pd.read_excel?

**head() vs. sample()**

In [128]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.sample(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
2072,1912,Stockholm,Athletics,Athletics,"BERNA, Tell Schirnding",USA,Men,3000m team,M,Gold
25627,2004,Athens,Weightlifting,Weightlifting,"POLSAK, Udomporn",THA,Women,53kg,W,Gold
3658,1920,Antwerp,Archery,Archery,"ALLAERT, Alphonse",BEL,Men,moving bird target 33m teams,M,Gold

**Functions to preprocess data. Modify the data, not the original files**

In [129]:
def preprocess(filename):
  """Transform the data. Change the dataframe and not the original csv files"""
  ...

preprocess(filename)

**Using python assert**

In [130]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape

(0, 10)

In [135]:
oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0

True

In [132]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)

In [134]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == 0)
print("All tests passed")

All tests passed

In [136]:
assert(oo[(oo.Year < 1896) & (oo.Year > 2004)].shape[0] == (0, 10))
#print("All tests passed")

AssertionError:

**Chaining and splitting over several rows. No inplace=True**

In [137]:
oo = pd.read_csv(filename, skiprows=5)
oo = oo.drop('Position', axis=1)
oo.head(3)

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze

In [ ]:
oo = (pd.read_csv(filename, skiprows=5)
      .drop('Position', axis=1)
)
oo.head(3)

In [138]:
last3 = pd.read_csv(filename, skiprows=5).sort_values(['Year', 'Athlete Name']).tail(3)
last3

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
26570,2004,Athens,Hockey,Hockey,"ZWEHL, Julia",GER,Women,hockey,W,Gold,1
25440,2004,Athens,Aquatics,Swimming,"ZWERING, Klaas-Erik",NED,Men,4x100m freestyle relay,M,Silver,2
25587,2004,Athens,Athletics,Athletics,"ZYKINA, Olesya",RUS,Women,4x400m relay,W,Silver,2

In [139]:
last3 = (pd.read_csv(filename, skiprows=5)
        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
26570,2004,Athens,Hockey,Hockey,"ZWEHL, Julia",GER,Women,hockey,W,Gold,1
25440,2004,Athens,Aquatics,Swimming,"ZWERING, Klaas-Erik",NED,Men,4x100m freestyle relay,M,Silver,2
25587,2004,Athens,Athletics,Athletics,"ZYKINA, Olesya",RUS,Women,4x400m relay,W,Silver,2

In [140]:
last3 = (pd.read_csv(filename, skiprows=5)
#        .sort_values(['Year', 'Athlete Name'])
        .tail(3)
)
last3

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access
/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: RangeIndex.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

**isin()**

In [141]:
oo.Year.isin?

In [142]:
years_of_interest = [1972, 1980, 1984, 1992, 2000, 2004]

In [143]:
oo[oo.Year.isin(years_of_interest)]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
12715,1972,Munich,Wrestling,Wrestling Free.,"TAYLOR, Christopher J.",USA,Men,+ 100kg (super heavyweight),M,Bronze
12716,1972,Munich,Wrestling,Wrestling Free.,"MEDVED, Aleksandr",URS,Men,+ 100kg (super heavyweight),M,Gold
12717,1972,Munich,Wrestling,Wrestling Free.,"DURALIEV, Osman",BUL,Men,+ 100kg (super heavyweight),M,Silver
12718,1972,Munich,Wrestling,Wrestling Gre-R,"DOLIPSCHI, Victor",ROU,Men,+ 100kg (super heavyweight),M,Bronze
12719,1972,Munich,Wrestling,Wrestling Gre-R,"ROSHCHIN, Anatoli",URS,Men,+ 100kg (super heavyweight),M,Gold
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [144]:
oo[~oo.Year.isin(years_of_interest)]

/usr/local/lib/python3.11/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
23156,1996,Atlanta,Fencing,Fencing,"FLESSEL-COLOVIC, Laura",FRA,Women,épée team,W,Gold
23157,1996,Atlanta,Fencing,Fencing,"MORESEE-PICHOT, Sophie",FRA,Women,épée team,W,Gold
23158,1996,Atlanta,Fencing,Fencing,"CHIESA, Laura",ITA,Women,épée team,W,Silver
23159,1996,Atlanta,Fencing,Fencing,"UGA, Elisa",ITA,Women,épée team,W,Silver
23160,1996,Atlanta,Fencing,Fencing,"ZALAFFI, Margherita",ITA,Women,épée team,W,Silver

**Finding and dealing with missing values**

In [145]:
oo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27174 entries, 0 to 27173
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          27174 non-null  int64
 1   City          27174 non-null  object
 2   Sport         27174 non-null  object
 3   Discipline    27174 non-null  object
 4   Athlete Name  27174 non-null  object
 5   NOC           27174 non-null  object
 6   Gender        27174 non-null  object
 7   Event         27174 non-null  object
 8   Event Gender  27174 non-null  object
 9   Medal         27174 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.1+ MB

## Creating Series and DataFrames

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]

In [ ]:
pd.Series(city)

In [ ]:
pd.DataFrame({"City": pd.Series(city),
              "Start Date": pd.Series(start_date)})

In [ ]:
pd.DataFrame({"City": city,
              "Start Date": start_date})

In [ ]:
pd.DataFrame(zip(city, start_date))

In [ ]:
pd.DataFrame(zip(city, start_date), columns=["City", "Start Date"])

## Working with dates

In [ ]:
import pandas as pd

In [ ]:
city = ["London", "Rio", "Tokyo"]
start_date = ["07-27-2012", "5th Aug, 2016", "23rd Jul, 2021"]
end_date = ["12th Aug, 2012", "21-08-2016", "8th Aug, 2021"]

In [ ]:
games = pd.DataFrame(zip(city, start_date, end_date), columns=["City", "Start Date", "End Date"])
games

In [ ]:
games.dtypes

In [ ]:
import re
import pandas as pd

search_string = "date"

[func for func in dir(pd) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
pd.to_datetime?

In [ ]:
#pd.to_datetime(games["Start Date"])

In [ ]:
pd.to_datetime(games["Start Date"], format='mixed')

In [ ]:
games["Start Date"] = pd.to_datetime(games["Start Date"], format='mixed')
games["End Date"] = pd.to_datetime(games["End Date"], format='mixed')
games["City"] = games.City.astype("string")
games

In [ ]:
games.dtypes

In [ ]:
games["End Date"]

In [ ]:
games["Start Date"]

In [ ]:
games["End Date"] - games["Start Date"]

In [ ]:
games = games.assign(duration=games["End Date"] - games["Start Date"])
games

In [ ]:
games.dtypes

## Combining DataFrames

In [ ]:
import pandas as pd

In [ ]:
start = pd.DataFrame({"city": ["London", "Rio", "Tokyo"],
                      "start_date": ["27th Jul, 2012", "5th Aug, 2016", "23rd July, 2021"]})
start

In [ ]:
end = pd.DataFrame({"City": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat?

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
end = pd.DataFrame({"city": ["London", "Tokyo", "Paris"],
                    "end_date": ["12th Aug, 2012", "8th Aug, 2021", "11th Aug, 2024"]})
end

In [ ]:
pd.concat([start, end], axis=0)

In [ ]:
pd.concat([start, end], axis=1)

**Inner join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge?

In [ ]:
pd.merge(left=start, right=end, on="city", how="inner")

**Outer join**

In [ ]:
start

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="outer")

**Left join**

In [ ]:
start

In [ ]:
pd.merge(left=start, right=end, on="city", how="left")

**Right join**

In [ ]:
end

In [ ]:
pd.merge(left=start, right=end, on="city", how="right")

## Combining Datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

preprocess()

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

In [ ]:
new_filename =  "olympics_2008.csv"
nw = pd.read_csv(new_filename)
nw.head(5)

In [ ]:
oo.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.columns

In [ ]:
oo.columns

In [ ]:
nw.columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']
nw.columns

In [ ]:
new_columns = ['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'Country_code',
       'Gender', 'Event', 'Event_gender', 'Medal', 'Result']

In [ ]:
nw = pd.read_csv(new_filename, names=new_columns)
nw.columns

In [ ]:
nw.columns = [column.capitalize() for column in nw.columns]
nw.columns

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
oo.columns

In [ ]:
nw.columns

In [ ]:
nw.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
nw.Result.unique()

In [ ]:
nw = nw.drop("Result", axis=1)
nw.sample(3)

In [ ]:
pd.concat([oo, nw], axis=0)

In [ ]:
pd.concat([oo, nw], axis=0).dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  return df

nw = preprocess_2008()
nw.sample(3)

## Working with Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.isna?

In [ ]:
nw.City.isna()

In [ ]:
nw.City.isna().sum()

In [ ]:
nw[nw.City.isna()]

In [ ]:
nw.City.unique()

In [ ]:
nw.shape

In [ ]:
import re

search_string = "na"

[func for func in dir(nw.City) if re.search(rf"{search_string}$", func, re.IGNORECASE)]

In [ ]:
nw.City.fillna?

In [ ]:
nw.City = nw.City.fillna(value="Beijing")
nw.City.unique()

In [ ]:
nw.Year

In [ ]:
nw.Year.unique()

In [ ]:
nw.Year = nw.Year.fillna(value=2008)
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Removing Missing Data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.info()

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna(how="all", axis=0)

In [ ]:
nw.dropna(how="any", axis=0)

In [ ]:
nw[nw.Sport.isna()]

In [ ]:
nw.dropna?

In [ ]:
nw.columns

In [ ]:
nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")

In [ ]:
nw = nw.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
nw.info()

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

##Working with Duplicates

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.shape

In [ ]:
nw.duplicated?

In [ ]:
nw.duplicated()

In [ ]:
nw.duplicated().sum()

In [ ]:
nw.loc[nw.duplicated(), :]

In [ ]:
nw.shape

In [ ]:
nw = nw.drop_duplicates()
nw.shape

In [ ]:
nw.columns

In [ ]:
athlete_multiple_events = nw.duplicated(subset=['Athlete Name', 'NOC', 'Gender'])
athlete_multiple_events

In [ ]:
nw.duplicated?

In [ ]:
nw.loc[athlete_multiple_events, :]

In [ ]:
nw.loc[athlete_multiple_events, :].sort_values("Athlete Name")

In [ ]:
nw.loc[nw["Athlete Name"] == "ZOU, Kai"]

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

## Validating data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw.Gender.unique()

In [ ]:
nw.loc[(nw["Event Gender"] == "M") & (nw.Gender != "Men")]

In [ ]:
nw.loc[(nw["Event Gender"] == "F") & (nw.Gender != "Women")]

In [ ]:
nw.loc[(nw.Gender == "Women") & ((nw["Event Gender"] != "W") & (nw["Event Gender"] != "X"))]

In [ ]:
nw.loc[(nw.Gender == "Men") & ((nw["Event Gender"] != "M") & (nw["Event Gender"] != "X"))]

In [ ]:
oo["Event Gender"].unique()

In [ ]:
oo.Gender.unique()

In [ ]:
oo.loc[(oo["Event Gender"] == "M") & (oo.Gender != "Men")]

In [ ]:
oo.loc[(oo["Event Gender"] == "F") & (oo.Gender != "Women")]

In [ ]:
oo.loc[(oo.Gender == "Women") & ((oo["Event Gender"] != "W") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Gender == "Men") & ((oo["Event Gender"] != "M") & (oo["Event Gender"] != "X"))]

In [ ]:
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
oo.loc[24676, "Gender"] = "Women"
oo.loc[(oo.Year == 2000) & (oo.Event == "marathon")]

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw.Year.unique()

In [ ]:
nw.City.unique()

In [ ]:
nw["Event Gender"].unique()

In [ ]:
nw["Event Gender"].unique().tolist()

In [ ]:
oo["Event Gender"].unique().tolist()

In [ ]:
nw["Event Gender"].unique().tolist() == oo["Event Gender"].unique().tolist()

In [ ]:
sorted(nw["Event Gender"].unique().tolist())

In [ ]:
sorted(oo["Event Gender"].unique().tolist())

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
print("Passes all tests ...")

In [ ]:
#assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
#assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
#assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
#print("Passes all tests ...")

In [ ]:
sorted(oo.Medal.unique().tolist())

In [ ]:
sorted(nw.Medal.unique().tolist())

In [ ]:
nw.Medal.str.capitalize()

In [ ]:
nw.Medal = nw.Medal.str.capitalize()
nw.sample(3)

In [ ]:
assert(sorted(nw["Event Gender"].unique().tolist()) == sorted(oo["Event Gender"].unique().tolist()))
assert(sorted(nw.Gender.unique().tolist()) == sorted(oo.Gender.unique().tolist()))
assert(sorted(nw.Medal.unique().tolist()) == sorted(oo.Medal.unique().tolist()))
print("Passes all tests ...")

In [ ]:
sorted(nw.Sport.unique().tolist())

In [ ]:
sorted(oo.Sport.unique().tolist())

In [ ]:
nw.NOC.unique()

In [ ]:
nw.Sport = nw.Sport.str.lower()
nw.Discipline = nw.Discipline.str.lower()
nw.Event = nw.Event.str.lower()
nw.NOC = nw.NOC.str.upper()
nw.sample(3)

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

nw = preprocess_2008()
nw.sample(3)

## Further Data Validation

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  return df

oo = preprocess()

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
medals = ['Gold', 'Silver', 'Bronze', 'Bronze', 'Gold']
medals

In [ ]:
medals[0]

In [ ]:
medals[1]

In [ ]:
len(medals)

In [ ]:
nw["Athlete Name"]

In [ ]:
import re

search_string = "split"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
nw["Athlete Name"].str.split?

In [ ]:
nw["Athlete Name"].str.split(", ")

In [ ]:
nw["Athlete Name"].str.split(", ").tolist()

In [ ]:
athlete_names = nw["Athlete Name"].str.split(", ").tolist()
athlete_names

In [ ]:
import re

search_string = "upper"

[func for func in dir(nw["Athlete Name"].str) if re.search(rf"{search_string}", func, re.IGNORECASE)]

In [ ]:
[athlete_name for athlete_name in athlete_names]

In [ ]:
[athlete_name[0] for athlete_name in athlete_names]

In [ ]:
[athlete_name[0].isupper() for athlete_name in athlete_names]

In [ ]:
len([item[0].isupper() for item in athlete_names])

In [ ]:
nw.info()

##Updating the dtypes

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  return df

oo = preprocess()
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
oo.dtypes

In [ ]:
def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

## Combine the datasets

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

In [ ]:
oo = preprocess()
oo.sample(3)

In [ ]:
oo.dtypes

In [ ]:
nw = preprocess_2008()
nw.sample(3)

In [ ]:
nw.dtypes

In [ ]:
pd.concat([oo, nw])

In [ ]:
pd.concat([oo, nw]).dtypes

In [ ]:
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
up.dtypes

##Plotting data

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df


def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
import matplotlib.pyplot as plt

**For the first Olympics, how many events were there for each of the different sports? Plot them using different graphs.**

In [ ]:
first_games = up[up.Year == 1896]
first_games

In [ ]:
first_games.Sport.value_counts()

In [ ]:
first_games.Sport.value_counts().plot?

In [ ]:
type(first_games.Sport.value_counts())

In [ ]:
dir(pd.Series)

In [ ]:
pd.Series.plot?

In [ ]:
first_games.Sport.value_counts().plot(kind='line')

In [ ]:
first_games.Sport.value_counts().plot(figsize=(10,3))

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 #.plot(figsize=(10,3))
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='bar')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot
 .bar()
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color='red')
)

In [ ]:
(first_games
 .Sport
 .value_counts()
 .plot(kind='barh', color=['blue', 'red'])
)

##Working with colormaps and Seaborn

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
games_2008 = up[up.Year == 2008]
games_2008.sample(3)

In [ ]:
(games_2008
 .Medal
 .value_counts())

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              )

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"])

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='seismic')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='coolwarm')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr')

In [ ]:
plt.figure(figsize=(5,3))
plt.title("Medals from the 2008 games")
sns.countplot(data=games_2008,
              x='Medal',
              order=["Gold", "Silver", "Bronze"],
              hue='Gender',
              palette='bwr_r')

##Working with groupby

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = (pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
        .drop('Position', axis=1)
  )
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ((up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC', 'Gender', 'Event'])
sp

In [ ]:
up.groupby("Year")

In [ ]:
type(up.groupby('Year'))

In [ ]:
up.groupby("Year").count()

In [ ]:
for group_key, group_value in up.groupby('Year'):
    print(group_key)
    print(group_value)

In [ ]:
type(group_value)

In [ ]:
up.groupby(['Year']).count()

In [ ]:
up.groupby("Year").size()

In [ ]:
up.groupby(['Year','NOC']).count()

In [ ]:
up.groupby(['Year','NOC'])['Medal'].count()

In [ ]:
up.groupby(['Year','NOC']).size()

In [ ]:
up.groupby(['Year','NOC','Medal']).size()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].max()

In [ ]:
up.groupby(['NOC'])['Year'].min()

In [ ]:
up.groupby(['NOC'])['Year'].agg(['min', 'max', 'count'])

##Reshaping data: Stacking, Unstacking and MultiIndex

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt


if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
sprints = up[(up.Year == 2008) & ( (up.Event == '100m') | (up.Event == '200m'))]
sprints

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack?

In [ ]:
sp.unstack('Gender', fill_value=0)

In [ ]:
(sp
 .unstack('Gender', fill_value=0)
 .unstack('Event', fill_value=0)
)

In [ ]:
sp.unstack?

In [ ]:
sp.unstack(['Gender', 'Event'], fill_value=0)

In [ ]:
sp = sprints.groupby(['NOC','Gender','Event']).size()
sp

In [ ]:
sp.unstack(level=1, fill_value=0)

In [ ]:
sprints_table = sp.unstack(level=1, fill_value=0).unstack(level=1, fill_value=0)
sprints_table

In [ ]:
sprints_NOC = sprints_table.stack("Gender")
sprints_NOC

In [ ]:
sprints_NOC.index

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), :]

In [ ]:
sprints_NOC.loc[('JAM',   'Men'), '100m']

In [ ]:
sprints_NOC.iloc[0, :]

In [ ]:
sprints_NOC.iloc[0, 0]

In [ ]:
sprints_NOC.stack?

In [ ]:
sprints_NOC.unstack?

## Challenge

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue and pink**

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

##Solution

**Using a line graph, plot the number of gold medals won by the USA male and female Olympians throughout the history of the Olympics?
Distinguish between the male and female Olympians in the line graph using blue (male) and pink (female)**

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_gold = up[(up.NOC == 'USA') & (up.Medal == 'Gold')]
usa_gold

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().index

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size()

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line')

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot?

In [ ]:
pd.Series.plot?

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['blue', 'pink'])

In [ ]:
usa_gold.groupby(['Year', 'Gender']).size().unstack('Gender').plot(kind='line', color=['pink', 'blue'])

**Using a bar chart, plot the 5 Olympians who have won the most gold medals from the dataset (1896 to 2008). When there is a tie, consider the number of silver medals, then bronze medals.**

In [ ]:
up.groupby(['Athlete Name','Medal']).size()

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

##Creating your own colormaps

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar')
)

In [ ]:
from matplotlib.colors import ListedColormap

In [ ]:
ListedColormap?

In [ ]:
gold_silver_bronze = ['#dbb40c','#c5c9c7','#a87900']

In [ ]:
colormap = ListedColormap(gold_silver_bronze)
colormap

In [ ]:
(up.groupby(['Athlete Name','Medal'])
.size()
.unstack('Medal', fill_value=0)
.sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)[['Gold', 'Silver', 'Bronze']]
.head(5)
.plot(kind='bar', colormap=colormap)
)

##Final Challenge

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

##Solution

For each Olympic year present in the dataset, show the US Olympian (and their sport) who has won the highest number of medals in that particular year.

- In the case of a tie, Gold > Silver > Bronze
- Include only one Olympian for each Olympic year i.e. If there are 2 Olympians in one year who have won exactly the same number and type of medals, then show only the first one based on sorting the names alphabetically by surname.

- You should show the the following columns for each Olympic year:
  - Athlete Name
  - Sport
  - Total

In [ ]:
!pip install --quiet pandas==2.0.2

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
pd.set_option("display.width", 100)

if not Path("olympics_1896_2004.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
if not Path("olympics_2008.csv").exists():
  !wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_2008.csv

filename = "olympics_1896_2004.csv"
print("Installed all of the necessary files for this section ...")

In [ ]:
def preprocess(filename = "olympics_1896_2004.csv"):
  """Preparing and transforming dataframe"""
  print(f"Preprocessing {filename} ...\n")
  ordered_medals = pd.api.types.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
  dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_gender": "category",
                "Medal": ordered_medals}
  df = pd.read_csv(filename, skiprows=5, dtype=dtype_mapper)
  df = df.drop('Position', axis=1)
  df["Event Gender"] = df["Event Gender"].astype("category")
  df.loc[24676, "Gender"] = "Women"
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  return df

def preprocess_2008(filename="olympics_2008.csv"):
  print(f"Preprocessing {filename} ...\n")
  df = pd.read_csv(filename)
  df.columns = ['City', 'Year', 'Sport', 'Discipline', 'Athlete Name', 'NOC',
       'Gender', 'Event', 'Event Gender', 'Medal', 'Result']
  df = df.drop("Result", axis=1)
  df.City = df.City.fillna(value="Beijing")
  df.Year = df.Year.fillna(value=2008)
  df = df.dropna(subset=['Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal'], how="all")
  df = df.drop_duplicates()
  df.Sport = df.Sport.str.lower()
  df.Discipline = df.Discipline.str.lower()
  df.Event = df.Event.str.lower()
  df.NOC = df.NOC.str.upper()
  df.Medal = df.Medal.str.capitalize()
  df.City = df.City.astype("string")
  df.Year = df.Year.astype(int)
  df.Sport = df.Sport.astype("string")
  df.Discipline = df.Discipline.astype("string")
  df["Athlete Name"] = df["Athlete Name"].astype("string")
  df.NOC = df.NOC.astype("string")
  df.Gender = df.Gender.astype("category")
  df.Event = df.Event.astype("string")
  df['Event Gender'] = df['Event Gender'].astype("category")
  medal_order = ["Bronze", "Silver", "Gold"]
  df.Medal = pd.Categorical(df.Medal, categories=medal_order, ordered=True)

  return df

oo = preprocess()
nw = preprocess_2008()
up = pd.concat([oo, nw])
up.sample(3)

In [ ]:
usa_olympian = up[up.NOC == 'USA']
usa_olympian

In [ ]:
usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport']).size()

In [ ]:
(usa_olympian.groupby(['Year', 'Athlete Name', 'Medal', 'Sport'])
.size()
.unstack('Medal', fill_value=0)
)

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
)
table

In [ ]:
table = (usa_olympian.groupby(['Year', 'Athlete Name', 'Sport', 'Medal'])
.size()
.unstack('Medal', fill_value=0)
.assign(Total=table['Gold']+table['Silver']+table['Bronze'])
.reset_index()
)
table

In [ ]:
for year, group in table.groupby('Year'):
  print(group)

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values('Total', ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False))

In [ ]:
for year, group in table.groupby('Year'):
  print(group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1))

In [ ]:
winners = [
    group.sort_values(['Total', 'Gold', 'Silver', 'Bronze', 'Athlete Name'], ascending=False).head(1)
    for year, group in table.groupby('Year')
]
winners

In [ ]:
winners[0]

In [ ]:
type(winners[0])

In [ ]:
pd.concat(winners)

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]]

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index()

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index?

In [ ]:
pd.DataFrame.reset_index?

In [ ]:
pd.concat(winners)[["Year",	"Athlete Name",	"Sport", "Total"]].reset_index(drop=True)

In [ ]:
#SDG